### ISSUE TITLE
Absentee of Units makes confusion

### ISSUE THREAD

**Issue by SweetyVolty** [mgth/LittleBigMouse#100]
"What are the units? Are they imperial or metric? Omg I'm too confused..."

Well, I an not confused actually, as a mech engineer my whole day gets by struggling with inches millimeters etc. My suggestion is there should be a tiny checkbox for conversion of metric/imperial, also a little marking of current unit too 

Loves ^^

**Comment by syborg64** [comment]
Initial config (One screen was suprisingly dead on) leads me to believe it's millimeters however the units can be abstracted away is only relative dimensions are used

**Comment by mgth** [comment]
mm
