### ISSUE TITLE
Disable for fullscreen apps

### ISSUE THREAD

**Issue by designgears** [mgth/LittleBigMouse#104]
Would it be possible to have an option to disable when a fullscreen app is detected? Just a slight annoyance remembering to disable it while playing games.

**Comment by Trickzington** [comment]
This would be amazing. If there was an option to make it detect fullscreen processes (and ideally, borderless windowed processes too) and disable lbm while they're in the foreground, that would be great.

**Comment by mollevi** [comment]
Hi! I dealt with this few minutes ago that my game got fallen out with your software namely every time i moved the cursor near the edge of my primary screen the cursor went higher and higher while it was blinking and half a second on the edge turned it to be on the upper corner (i think this duation is dependig on the preferences i set up) I think it is not a problem hard to be solved and we would appreciate such an act of grace. Thank you all, anyway this is a very helpful app.

**Comment by phynias** [comment]
maybe another option is to have a list of apps. when those apps are running this one is disabled.

**Comment by Xenataur** [comment]
Ah I finally figured out this is what was causing my issues in Valorant!

Any movement on this? Is the recommended solution to roll back to 4.2.7124.42685?

**Comment by chaseholdren** [comment]
> Ah I finally figured out this is what was causing my issues in Valorant!
> 
> Any movement on this? Is the recommended solution to roll back to 4.1.6598.15330? @mgth

wait does that version solve this problem??
