### ISSUE TITLE
Identical monitors still merge together

### ISSUE THREAD

**Issue by wwboynton** [mgth/LittleBigMouse#109]
So Issue #33 seems like it has regressed, or something. I know those changes were eliminated eventually when the code was refactored, but something is still weird here.

I have two MSI Optix AG32C monitors which report a `serial` of `10000000` and do not have a `SerialNo` value.

[On line #333-334 of `ScreenConfig.cs`](https://github.com/mgth/LittleBigMouse/blob/3d81c0713c1015f5d47b49cadf29d03f7a954102/LittleBigMouse/ScreenConfig/ScreenConfig.cs#L333), we get this:

```cpp
            var monitor = MonitorsService.Monitors.FirstOrDefault(
                d => monitorId == d.Edid.ManufacturerCode + d.Edid.ProductCode + "_" + d.Edid.Serial);
```

I'm no C++ programmer, but that seems to me like it's reading the EDID data and creating a "unique" monitor ID by concatenating the manufacturer code, product code, and device serial. In my case, all of those values are the same between the two monitors, so we get the same issue as in #33. 

What's interesting is that by following directions for an EDID override by modifying the `EDID` registry value at `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\DISPLAY\MSI1462\1&3241a98&0&UID3324\Device Parameters`, I see [the changes](https://imgur.com/t9HKaYr) reflected in LBM on restart. One would think that altering any of those values for one monitor but not the other would create a unique ID string, but it doesn't seem to be resolving the issue. So now I'm _really_ confused, and certainly well out of my depth.

And if this _is_ still the problem and the Device ID is being cached by LBM or something, then I'm curious why we wouldn't just use something already unique to the device, like the Windows `ContainerId` value or even just the `DeviceName`, which are all (I think) guaranteed to be unique per-monitor.

**Comment by wwboynton** [comment]
Yeah, confirming that this issue persists through a reinstall of the application including cleaning out the stuff in `AppData\Local` so I don't think it's a caching thing. Is the method of grabbing the EDID values for generating the ID for some reason different than the one used for rendering those values in the "Info" panel of the application?

**Comment by mollevi** [comment]
I dont know if my problem fits this topic but hell when i turn on screen split or i turn off dual mode ignoring the secondary monitor the app still moves the mouse on the edge of the sceen but since 2nd screen is off the cursor stay there not moving back to its original position after getting it back from the edge

**Comment by ehsfball78** [comment]
Seeing the same thing.  I have dual Lenovo P27u-10 monitors that are merging together, so the cursor will never move to the 2nd monitor.  I downloaded the source to attempt to debug this issue, but it appears the HLAB project isn't available.

**Comment by DieQuelle** [comment]
For a moment I thought its a problem with my configuration.
Maybe this is also intereseting:
IT seems that the Connection Method (HDMI or DP) is also a factor.
I just switched an old amazon HDMI cable to a better 4K Displayport Cable an now i got this issue.

Of course this are both the same monitors.
My configuration:

![image](https://user-images.githubusercontent.com/6370335/73592815-8dd2b600-44fe-11ea-8896-0d255af4383a.png)

**Comment by FakeNeth** [comment]
Having the same issue. Have a 1080p monitors on both sides of a 4k monitor. The 2 1080p monitors are identical models, and the software keeps stacking them to the left of the 4k monitor.

Makes the software unusable for this type of environment :(

**Comment by tinyoverflow** [comment]
This issue still persists. I have two AOC 27G1G4 and both locations get merged together.
