### ISSUE TITLE
LBM does not detect when Windows decides to renumber monitors

### ISSUE THREAD

**Issue by vanarebane** [mgth/LittleBigMouse#112]
Hi!

Here is the image of how differently the monitors are numbered and my setup: https://imgur.com/gallery/TNXDshH

**Steps to reproduce the bug:**
**1.** Have three monitors with 2xDP and 1xHDMI plugged in. Windows numbers them 1=DP, 2=DP, 3=HDMI (because count DP first, then HDMI)
**2.** Setup LBM for monitor 1 and 2.
**3.** Disconnect (I just need to turn it off) monitor no 2. Windows decides it's nicer if the monitors are numbered now 1=DP, 2=HDMI.
**4.** LBM now blocks the movement to the HDMI monitor (on the right), as the HDMI is now number 2 and number 2 is supposed to be on left.

**Solution:**
LBM, instead of windows monitor numbering, use monitor unique ID/serial instead.

**Comment by buchtufer** [comment]
Similar issue with 2 screens and HDMI switch.

**Steps to reproduce:**
**1.** 2 monitors: right is "Display 1" and larger, left is "Display 2" with switch for HDMI inputs.
**2.** LBM is configured (see config.txt, 1.png).
**3.** Button is pressed on HDMI switch, changing monitors such that only right is active on this PC.
**4.** Right display now prevents cursor from moving below a certain point (see 2.png).
**5.** If HDMI switch turns left monitor back to this PC, LBM resumes as normal with no issue.

I would be willing to try to troubleshoot this and submit a pull request, but the "HLAB" folder is not included in the project so I am not able to debug or build (see HLAB.png).

![1](https://user-images.githubusercontent.com/64800889/80997215-fe93b200-8e0e-11ea-899e-9015896d23b3.png)
![2](https://user-images.githubusercontent.com/64800889/80997229-018ea280-8e0f-11ea-83db-28a8dbc4a3d2.png)
[config.txt](https://github.com/mgth/LittleBigMouse/files/4576321/config.txt)
![HLAB](https://user-images.githubusercontent.com/64800889/80997233-03586600-8e0f-11ea-80ff-50aa8452e7bc.png)
