### ISSUE TITLE
Using UNDO corrupted monitor recognition

### ISSUE THREAD

**Issue by MikeFarrington** [mgth/LittleBigMouse#113]
In running LBM for the first time.  On first launch, all monitors were detected properly.  I was trying to familiarize myself with the options by applying them one by one.  At the end, I hit UNDO many times to revert back to the original settings.  After doing so, my number 2 monitor disappeared and now I only see 1 and 3.

This may be related to #109 as monitors 2 and 3 are the same make/model.  Oddly, when showing the details for monitor 3 it shows monitor 2's refresh rate.  (I'm running the two identical monitors at different refresh rates due to the use of different DisplayPort extenders who handle 4K at a distance differently).

Deleting the LBM folder in %LocalAppData% did not revert things the way I thought it might.

If I apply the settings when it shows monitors 1 and 3 only, I can move the mouse between monitors 1 and 2, but cannot move to 3.

I'm also experiencing #99, Failure to write to registry on exit.  I mention this just in case they are related issues.

I'm running Windows Server 2019 (Build 1809).  The monitors that seem to be getting merged are ASUS model PB297Q running at 4K (one at 60Hz, one at 30Hz).

**Comment by PharaohJoe** [comment]
I'm having the EXACT same issues. Two of my monitors are the same make/model and one of them isn't detected. Only monitors 1 and 3 are detected. 

I'm also experiencing the "Cannot write to the registry key." error.  It occurs whenever I right click on the tray icon and attempt to stop, start, or exit the application. All of these choices give the error.
