### ISSUE TITLE
2nd screen is NOT detected

### ISSUE THREAD

**Issue by gabrielemarra** [mgth/LittleBigMouse#115]
The main display is detected properly but the second display (HDMI output from my notebook) is not detected by the program

If I disable the main display and I open LBM, there's no display showed in the GUI

I don't know what it could be the problem

Here the screenshots: https://imgur.com/a/3vNHrLl

**Comment by magnusroe** [comment]
I also get only one monitor detected.
Both mine are connected by DP from the same video card, the one detected is the primary and is UHD, while the other is regular HD and HDR enabled.
