### ISSUE TITLE
VCP Drive settings not being applied

### ISSUE THREAD

**Issue by scainburger** [mgth/LittleBigMouse#117]
I went to the VCP tab to adjust my colour settings, and the "Drive" sliders are not applying their settings. Now they are stuck at extremely low values, the background colour of the number changes to orange and never goes green if I drag it above a value of 2. Please see https://i.imgur.com/l9SEACJ.png

**Comment by scainburger** [comment]
Is there a way I can manually revert this? i.e. is this being changed through a registry value or something similar I can access and set to the values I want?

**Comment by mgth** [comment]
Many monitors do not support drive change. It will be disable  in next version when monitor do not support it.
