### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by syborg64** [mgth/LittleBigMouse#128]
Reloading the control software completely changes the config
'Copy settings' but nowhere to paste
input values randomly decide they can't accept this value and go for some random value instead of what was just typed
X values affect Y values and vice versa, however not according to the aspect ratio so unusable (there was a way to modify that but it felt random) and the lock button does literally nothing
rulers were not aligned even when correct setup was eventually achieved.
Worked once, then after adjusting never turned on again.
Start button has no feedback
First thing that happened, my cursor was yeeted off my main display where the control window was, had to kill it with taskmanager using only keyboard
typos caused everything to merge to 0, making editing impossible-> resulting to reset and lost progress
undo button doesn't work
I have a headache
Never have I ever uninstalled software so quickly in my life

**Comment by dashrava** [comment]
It is pretty fiddly, but if you give it the tiniest bit of effort instead of facerolling your way into a ragequit, you can tune it properly once and it'll Just Work afterwards. Been using the same config for a year now myself.
