### ISSUE TITLE
Cursor Skips Over Third Monitor

### ISSUE THREAD

**Issue by Sputnikcer** [mgth/LittleBigMouse#132]
I am using a four-monitor setup. My first and third monitors are 27-inch 1080p displays. My second monitor (the main one that I use) is a 27-inch 1440p display. My fourth monitor is a 21.5 inch 1080p display. 

When the fourth monitor is positioned under the second monitor in the software, the cursor will not move to the third monitor, and will not cross the right side of the second monitor. 

When the fourth monitor is positioned on the far right in the software, the cursor will skip over the third monitor entirely. I cannot seem to use the third monitor at all in LittleBigMouse

When I run the LittleBigMouse application on the third monitor, the cursor can remain on that monitor until the cursor moves onto another monitor, in which case the monitor will not be able to move back onto the third monitor.

Edit: Other people have the same problem when two monitors are the same brand and model, apparently. It's a recurring issue, found here as well: https://github.com/mgth/LittleBigMouse/issues/80

When LittleBigMouse starts up, I have to move the locations of the monitors so that I see the third monitor; it doesn't start the application with it visible. Maybe this is a part of the problem?

**Comment by Sputnikcer** [comment]
Hotfix: There are four buttons on the top right corner of the application. I clicked the button that has a monitor with a question mark in the center. I went to the third display and changed the last letter of the model number to something else. This fixed the issue.

I'm not sure if this will damage my monitor or change something about it in hardware memory or something, but it works now, so that's neat I guess. 

Just in case this helps anyone with the same problem, or help the developer implement a proper fix for it potentially.

**Comment by ItsANoBrainer** [comment]
Whats the hotfix? I cant see the comment anymore

**Comment by Sputnikcer** [comment]
> Whats the hotfix? I cant see the comment anymore

I deleted comments regarding the fix because I was just an idiot. It didn't fix it; I just hadn't applied the changes. Sorry for the confusion and for getting your hopes up. I am currently looking into finding a way to make my third monitor report as something else in an attempt to fix it to see if that changes anything.

**Comment by NPFFTW** [comment]
Exactly the same issue. Two identical monitors overlap in the UI and moving them does nothing -- one of the monitors becomes completely inaccessible.
