### ISSUE TITLE
Very high RAM usage

### ISSUE THREAD

**Issue by FaolanDev** [mgth/LittleBigMouse#133]
![image](https://user-images.githubusercontent.com/19892966/90292830-96775200-de7a-11ea-9b34-9b47fac2318d.png)

As you can see in this case it appears to be using 4.5GB of RAM but I have seen it at 1GB fairly commonly (which I assume is unintentional). Happens fairly often, I do have 32GB of RAM so I don't know if that affects it somehow but just saying what I know.

Update: As of a couple days later is is now using 11GB of RAM which is becoming a problem. Although I don't know why, it's safe to assume the amount grows when a computer is on (it sleeps overnight) not sure if a slow memory leak or otherwise.

**Comment by scrhall** [comment]
the same happens to me. I use a script to stop and start de daemon each hour

**Comment by hammerschaedel** [comment]
<img width="720" alt="2021-01-02 10_31_16-TaskManagerMain" src="https://user-images.githubusercontent.com/21966062/103454721-12b5e900-4ce7-11eb-80c5-3f59345d1c6f.png">
same here after leaving the pc over night on....

**Comment by jrfnl** [comment]
@scrhall Care to share the script ? Could be useful for others too.

**Comment by scrhall** [comment]
I used the Windows Task Scheduler, but I had to stop using the App, although I have 32gb of Ram, the PC would freeze from time to time.
