### ISSUE TITLE
LBM launches, but nothing appears when selecting any of the Tabs

### ISSUE THREAD

**Issue by afroeagle** [mgth/LittleBigMouse#137]
Thank you for this tool, I greatly appreciate you and your work.

1. Using the pre-compiled Windows executable LittleBigMouse_4.2.7124.42685.exe on Windows 10 Version 2004 , OS build 19041.450 with dual 27" monitors connected over DisplayPort (one 2560 x 1440 and the other 3840 x 2160) via a Nvidia GTX 1080ti 
2. The app installs correctly and launches
3. Nothing appears in the large center portion of the app window (see attached photo)
4. Selecting any of the Tabs in the top left corner of the app windows has no effect
5. I have tried running both the app and the daemon as Administrator with no effect
6. I have tried rebooting the computer
![image](https://user-images.githubusercontent.com/46386620/92433254-b89e8000-f159-11ea-80b1-a42b8f03775f.png)

Although I have read the documentation/Wiki, I have not found a solution to this issue. If I am doing something wrong, please let me know!

**Comment by Openning** [comment]
+1 -- I also have this same issue

**Comment by ckschu** [comment]
Same here
