### ISSUE TITLE
Anything similar for Mac?

### ISSUE THREAD

**Issue by merlinpatt** [mgth/LittleBigMouse#138]
I'm not asking you to port this to Mac since I imagine that would be challenging, but have you come across anything similar for Mac?

**Comment by Leonetienne** [comment]
That's not an issue.
Should be closed

**Comment by merlinpatt** [comment]
That depends on your point of view on what an Issue should be. Some repos use Issues for questions and discussions.

**Comment by Leonetienne** [comment]
But this is wrong. Every issue blames the authors for doing something wrong. This is not a forum.
Use the comment section at the commits. Or other forums like reddit or stackexchange.
But don't open an issue. Just as you would not open a ticket at steam just to ask them what games to play on mac.

**Comment by merlinpatt** [comment]
I'll let the maintainer of the repo decide if opening an issue to ask a question is acceptable or not. Having an open issue does not automatically say that the author is doing something wrong. You're free to have that philosophy for your own repos and projects, but don't try to control someone else's repos and projects. I could go into greater detail but I won't because this is now sidetracking into a forum discussion (that you started) that is completely unrelated to the original point of this issue/question. As such, I will no longer respond to you.

**Comment by mgth** [comment]
Sorry, I don't know anything about mac. See no offence, nothing wrong with your question, but I need to close to keep bug tracking clean.

**Comment by merlinpatt** [comment]
Yeah, totally fine. :-) Just wondering if you had seen anything similar. As far as I can tell, I may have to build it myself, if it's even possible. I fear Apple may have it locked down

**Comment by immustard** [comment]
> for posterity: cursr.app currently has similar functionality plus a software kvm, but is a freemium closed source product对于后代：Cursr.App当前具有相似的功能和软件KVM，但是免费的封闭源产品

thx

**Comment by immustard** [comment]
> for posterity: cursr.app currently has similar functionality plus a software kvm, but is a freemium closed source product

thx
