### ISSUE TITLE
[Fresh install] User interface not opening after starting from the win start menu

### ISSUE THREAD

**Issue by Leonetienne** [mgth/LittleBigMouse#140]
Bascially the title, but the thread does exist and take up an entire thread of cpu time.
Open it 16 times on my 16 thread cpu, and it's pinned at 100%

**Comment by Leonetienne** [comment]
Oh yea, it doesn't start by opening it manually, not even with compatibility mode on.

**Comment by Leonetienne** [comment]
Never mind, just took an eternity to launch the ui lol

**Comment by Josverl** [comment]
Just adding a note that the 1st launch still has the glitch that it locks up and shows a partially initialized / blurred display.
required killing the app and re-starting, then everything was good.

i can only assume that it it some initialization / missing configuration lacking on 1st launch
