### ISSUE TITLE
Add a code license

### ISSUE THREAD

**Issue by eykamp** [mgth/LittleBigMouse#141]
Please add a license to this project so I know if/how I can share it.  Ideally MIT.

Thanks!

**Comment by jmahlers** [comment]
^^Adding a license would allow for broader use of this utility

**Comment by lukasubo** [comment]
Searching "license" in this repository shows that the license headers specify GPLv3.

**Comment by jmahlers** [comment]
Ah thanks, I just made a pull request so that the license will be obvious from the main github page.
