### ISSUE TITLE
Need to know where the configuration is stored to clear it out completely - Looking to reset the program

### ISSUE THREAD

**Issue by itsitrio** [mgth/LittleBigMouse#147]
I work for an MSP, and one of my clients is using this program on a Surface device with two attached monitors. They take the device between the office and home, and sometimes the display configuration in LBM gets messed up and won't allow the mouse to traverse beyond the primary monitor, or worse, the arrangement gets all messed up. Normally, I am able to just reset the size of the monitors (It never detects the right physical dimensions), rearrange, and resize to the correct physical dimensions in the software to get them working again. Today, we were unable to do so, as when we would start the daemon again, it would lock the mouse to the primary monitor, even though the arrangement was correct.

We also have noticed that sometimes the size of the monitors becomes skewed in the config program, so it makes me wonder if not all the values typed for the display size are actually being written to the aforementioned configuration store.

My question is - where is the LBM display configuration stored so that I can wipe it completely off their system, reinstall the program and start over. 

We also would like better profile management, as this user brings this device between two different display setups. 

Thank you

**Comment by mgth** [comment]
HKEY_CURRENT_USER\SOFTWARE\Mgth\LittleBigMouse

**Comment by wurlog** [comment]
thank you very much!
