### ISSUE TITLE
Where to find the HLab dependcy

### ISSUE THREAD

**Issue by kelince** [mgth/LittleBigMouse#148]
I try to build the LBM, in thant sln, there are HLab projects depended,
Where could I find the HLab dependcy?

**Comment by gribuser** [comment]
See #131 discussion

**Comment by mgth** [comment]
HLab is now available at https://github.com/CHMP-HLab/HLab
But don't expect too much about it, it is still a work on progress for another project.
And I'm still working on some memory leak due to wrong events usage. It should be cleaned up for the end of the year.

**Comment by gribuser** [comment]
HLab.Argyll is still missing

**Comment by voidptr** [comment]
As are HLab.Windows.API, Monitors, and MonitorVcp

**Comment by wickedlizerd** [comment]
Any updates on this? It's been over 5 months. Can we still not build LBM ourselves?

**Comment by strazto** [comment]
From @mgth 's recent commit activity, I think this issue may be addressed
