### ISSUE TITLE
Make windows the same height and size across monitors

### ISSUE THREAD

**Issue by adamerose** [mgth/LittleBigMouse#152]
Sync window size and position across monitors in addition to the mouse cursor, here's an example of them being out of sync:
![image](https://user-images.githubusercontent.com/10884874/100513884-56dd2900-313e-11eb-9ef1-1c6a31c2f379.png)

And here's how it ideally should look:
![image](https://user-images.githubusercontent.com/10884874/100513929-c3f0be80-313e-11eb-804f-148d8f09c57e.png)

I got [mine](https://www.screencast.com/t/mfzIk1NPyt) looking like the 2nd pic by [creating a custom resolution using AMD super resolution](https://www.reddit.com/r/Amd/comments/d0418l/is_it_possible_to_create_custom_virtual/) and setting it to get similar real world DPIs based on my two monitor sizes. In this case I had my 27 inch monitor at 2560x1440 and my 24 inch monitor at 2240x1260, but it would be cool if this project could fix this automatically.

**Comment by mgth** [comment]
No easy way of doing this, unless virtual resolution, but not the object of this software
