### ISSUE TITLE
Plugging monitors in and out makes half the screen inaccessible

### ISSUE THREAD

**Issue by Ariane-B** [mgth/LittleBigMouse#153]
**My setup - Software:**
- Windows 10, 20H2 update.
- Nvidia Quadro Desktop/Quadro Notebook Driver Release 450 (version 443.32)
- Little Big Mouse version... I think it's the latest, since I checked the "Auto Check for update" box and it's not telling me about any updates, but there doesn't seem to be a way to check the version I have in the interface. Anyway I installed it just a couple of weeks ago, and this repository doesn't seem to show any recent releases, so I probably have the latest.

**My setup - Hardware:**
- Nvidia Quadro P2000 Max-Q graphics (Intel integrated graphics are 100 % disabled in the BIOS)
- Left: A 15-inch Lenovo P1 laptop with a 4K touchscreen.
- Center: A 24-inch 1080p monitor, plugged into the laptop's HDMI port.
- Right: A 24-inch 1080p monitor, plugged into a Lenovo dock's HDMI port.
- The Lenovo dock is plugged into the laptop through Thunderbolt 3.

Neither of the external monitors natively supports HDMI. They're both plugged in through DVI-to-HDMI converters.

**How to trigger the issue**

There are three things I frequently do that'll often trigger the issue. 

- Unplug the center monitor to plug it into my personal PC, and back into the laptop.
- Unplug everything from the laptop and use the laptop by itself.
- Let the PC go to sleep and/or hibernate, then wake it up. The issue here is possibly that the Thunderbolt dock wakes up after the PC does, and the monitor plugged in through Thunderbolt is thus added a little late, resulting in what's effectively an unplug/plug event.

**What the issue is**

The bottom half of the 4K screen is inaccessible to the mouse, except when the User Account Control popup is shown. It's possible to interact with *some* elements in the bottom half of the screen if I use the touchscreen, but most of them don't work.

**Workaround**

The issue can be fixed by pressing the Windows key on the keyboard (since the Start menu button can't be reached) and searching for Little Big Mouse, opening it and, while staying in the upper half of the screen (because the cursor won't reach the bottom half), going into move or resize mode, doing something to the laptop screen to unlock the ▶ apply button, and using the touchscreen to press the ▶ apply button.

That causes Little Big Mouse to "refresh" its configuration and everything's fine again, until the next monitor change.

If I didn't have a touchscreen to reach that inaccessible ▶ apply button, I think I'd have to kill Little Big Mouse (not sure if I actually could with just my keyboard and half a screen's worth of mouse real estate) or straight up reboot to get control of my PC back, which is a pretty major issue IMO.

**What I think you should work on:**

Here are the things I think should be fixed:

1. The ▶ apply button should never be disabled. I shouldn't need to drag a monitor somewhere then back where it originally was to "refresh" Little Big Mouse.
2. It would be nice if there were an easy to reach "refresh"/"re-initialize" button (that would basically do the same as changing nothing + pressing ▶ apply). Ideally, if it were in the top half of the screen, it would be great lol.
3. Ideally, Little Big Mouse should automatically refresh its config after monitors are plugged in or out. I don't know if it's technically possible, but it would be cool if plugging monitors in and out didn't require additional manual steps.

**Comment by FrankPeters** [comment]
I'm experiencing the same issue on a daily basis as I dock and undock my laptop from my monitor multiple times per day. I've adopted the workaround to kill LBM and then restart it.

**Comment by grantstrotter** [comment]
I'm doing the same as Frank Peters. I'm getting used to killing the process in task manager with the keyboard, as the mouse generally isn't able to do the job when this bug occurs.
