### ISSUE TITLE
[Bug] can't move cursor to some area after unplug monitor directly

### ISSUE THREAD

**Issue by GrayXu** [mgth/LittleBigMouse#158]
This is a great tool!

But I just found I have to close/stop it manually when I unplug monitor, otherwise I can't move cursor to some area...  

So, It would be better if LittleBigMouse can detect my monitor is attached or not and stop automatically. (And I think this feature is easy to implement? since LittleBigMouse can detect monitor status already

Thanks!

**Comment by adrensnyder** [comment]
I have the same problem. I have 3 monitors but only 2 usually on. After i use the third monitor alone i can't mouse mouse over some areas.

**Comment by turtlebasket** [comment]
Having this problem as well.

**Comment by spinda** [comment]
I worked around this problem with an AutoHotKey script that restarts the LittleBigMouse daemon on monitor events:

```ahk
OnMessage(0x219, "MsgMonitor")
MsgMonitor(wParam, lParam, msg)
{
  SetTimer, RestartDaemon, 250
}
return

RestartDaemon:
SetTimer, RestartDaemon, Off
RunWait, "C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe" --stop
RunWait, "C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe" --start
```

Configure this to run elevated on login (e.g., through Task Scheduler).

**Comment by GrayXu** [comment]
> I worked around this problem with an AutoHotKey script that restarts the LittleBigMouse daemon on monitor events:
> 
> ```ahk
> OnMessage(0x219, "MsgMonitor")
> MsgMonitor(wParam, lParam, msg)
> {
>   SetTimer, RestartDaemon, 250
> }
> return
> 
> RestartDaemon:
> SetTimer, RestartDaemon, Off
> RunWait, "C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe" --stop
> RunWait, "C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe" --start
> ```
> 
> Configure this to run elevated on login (e.g., through Task Scheduler).

Thx! I will try!
