### ISSUE TITLE
LBM does not detect laptop monitor

### ISSUE THREAD

**Issue by yomach** [mgth/LittleBigMouse#159]
Hey,
I have the classical problem: a Laptop with a high resolution 14" screen and an external 24" screen. I downloaded LBM to fix the mouse transitions, but LBM only detects the 24" screen :\ See attached image.
The computer is a Lenovo E14.

![image](https://user-images.githubusercontent.com/53370976/103874022-55a60100-50d9-11eb-8ed1-a5c77ba1dcbf.png)

**Comment by pvries86** [comment]
I have the same issue with my HP Elitebook 830 G7.
It does work on the Microsoft Surface Pro X.

**Comment by pvries86** [comment]
> Hey,
> I have the classical problem: a Laptop with a high resolution 14" screen and an external 24" screen. I downloaded LBM to fix the mouse transitions, but LBM only detects the 24" screen :\ See attached image.
> The computer is a Lenovo E14.
> 
> ![image](https://user-images.githubusercontent.com/53370976/103874022-55a60100-50d9-11eb-8ed1-a5c77ba1dcbf.png)

My laptop monitor was hiding between my secondary monitor. After moving the secondary screen, I could see the laptop monitor.

**Comment by RmK9** [comment]
Had the same issue, while moving the monitors I could find the 1st (laptop screen) underneath and just moved it in properly. I guess this issue could be restructured to work on fixing initial display positions so it doesn't cause some display to be overlapping (and therefore hiding) other display.
