### ISSUE TITLE
LBM Broke my monitor color

### ISSUE THREAD

**Issue by Rolodo** [mgth/LittleBigMouse#161]
I can no longer change the color of my monitor and it's stuck without red
https://imgur.com/a/bv9SEw4
when changing it back
https://imgur.com/a/74EKz5b
The monitor stay blue

`{
  "Config": {
    "Id": "ACI27E2_D2LMTF007809_0.ACR071C__0.BOE0747_0003_0",
    "AllScreens": [
      {
        "Id": "ACI27E2_D2LMTF007809_0",
        "IdResolution": "1920x1080",
        "Primary": false,
        "Orientation": 0,
        "PhysicalRotated": {
          "Borders": "20,20,20,20",
          "Bounds": "0,0,598,336",
          "OutsideBounds": "-20,-20,638,376"
        },
        "InMm": {
          "Borders": "20,20,20,20",
          "Bounds": "-638,0,598,336",
          "OutsideBounds": "-658,-20,638,376"
        },
        "InMmUnrotated": {
          "Borders": "20,20,20,20",
          "Bounds": "-638,0,598,336",
          "OutsideBounds": "-658,-20,638,376"
        },
        "InPixel": {
          "Borders": "0,0,0,0",
          "Bounds": "-1920,0,1920,1080",
          "OutsideBounds": "-1920,0,1920,1080"
        },
        "InDip": {
          "Borders": "0,0,0,0",
          "Bounds": "-960,0,1920,1080",
          "OutsideBounds": "-960,0,1920,1080"
        },
        "RealPitch": {
          "X": 0.31145833333333334,
          "Y": 0.31111111111111112
        },
        "PhysicalRatio": {
          "X": 1.0,
          "Y": 1.0
        },
        "Pitch": {
          "X": 0.31145833333333334,
          "Y": 0.31111111111111112
        },
        "OverallBoundsWithoutThisInMm": "0,0,984,340",
        "GuiLocation": "0,0,0,0",
        "WinDpiX": 96.0,
        "WinDpiY": 96.0,
        "RawDpi": {
          "X": 81.0,
          "Y": 81.0
        },
        "EffectiveDpi": {
          "X": 96.0,
          "Y": 96.0
        },
        "DpiAwareAngularDpi": {
          "X": 81.0,
          "Y": 81.0
        },
        "WpfToPixelRatio": {
          "X": 1.0,
          "Y": 1.0
        },
        "PixelToDipRatio": {
          "X": 1.0,
          "Y": 1.0
        },
        "PhysicalToPixelRatio": {
          "X": 3.2107023411371238,
          "Y": 3.2142857142857144
        },
        "MmToDipRatio": {
          "X": 3.2107023411371238,
          "Y": 3.2142857142857144
        },
        "RealDpi": {
          "X": 81.551839464882946,
          "Y": 81.642857142857139
        },
        "DpiX": {
          "X": 81.551839464882946,
          "Y": 81.642857142857139
        },
        "RealDpiAvg": 81.597360994565918
      },
      {
        "Id": "ACR071C__0",
        "IdResolution": "3840x2160",
        "Primary": true,
        "Orientation": 0,
        "PhysicalRotated": {
          "Borders": "20,20,20,20",
          "Bounds": "0,0,600,340",
          "OutsideBounds": "-20,-20,640,380"
        },
        "InMm": {
          "Borders": "20,20,20,20",
          "Bounds": "0,0,600,340",
          "OutsideBounds": "-20,-20,640,380"
        },
        "InMmUnrotated": {
          "Borders": "20,20,20,20",
          "Bounds": "0,0,600,340",
          "OutsideBounds": "-20,-20,640,380"
        },
        "InPixel": {
          "Borders": "0,0,0,0",
          "Bounds": "0,0,3840,2160",
          "OutsideBounds": "0,0,3840,2160"
        },
        "InDip": {
          "Borders": "0,0,0,0",
          "Bounds": "0,0,1920,1080",
          "OutsideBounds": "0,0,1920,1080"
        },
        "RealPitch": {
          "X": 0.15625,
          "Y": 0.15740740740740741
        },
        "PhysicalRatio": {
          "X": 1.0,
          "Y": 1.0
        },
        "Pitch": {
          "X": 0.15625,
          "Y": 0.15740740740740741
        },
        "OverallBoundsWithoutThisInMm": "-638,0,1622,336",
        "GuiLocation": "0,0,0,0",
        "WinDpiX": 192.0,
        "WinDpiY": 192.0,
        "RawDpi": {
          "X": 162.0,
          "Y": 161.0
        },
        "EffectiveDpi": {
          "X": 192.0,
          "Y": 192.0
        },
        "DpiAwareAngularDpi": {
          "X": 161.0,
          "Y": 160.0
        },
        "WpfToPixelRatio": {
          "X": 2.0,
          "Y": 2.0
        },
        "PixelToDipRatio": {
          "X": 0.5,
          "Y": 0.5
        },
        "PhysicalToPixelRatio": {
          "X": 6.4,
          "Y": 6.3529411764705879
        },
        "MmToDipRatio": {
          "X": 3.2,
          "Y": 3.1764705882352939
        },
        "RealDpi": {
          "X": 162.56,
          "Y": 161.36470588235292
        },
        "DpiX": {
          "X": 162.56,
          "Y": 161.36470588235292
        },
        "RealDpiAvg": 161.96345560727312
      },
      {
        "Id": "BOE0747_0003_0",
        "IdResolution": "1920x1080",
        "Primary": false,
        "Orientation": 0,
        "PhysicalRotated": {
          "Borders": "20,20,20,20",
          "Bounds": "0,0,344,194",
          "OutsideBounds": "-20,-20,384,234"
        },
        "InMm": {
          "Borders": "20,20,20,20",
          "Bounds": "640,0,344,194",
          "OutsideBounds": "620,-20,384,234"
        },
        "InMmUnrotated": {
          "Borders": "20,20,20,20",
          "Bounds": "640,0,344,194",
          "OutsideBounds": "620,-20,384,234"
        },
        "InPixel": {
          "Borders": "0,0,0,0",
          "Bounds": "3840,0,1920,1080",
          "OutsideBounds": "3840,0,1920,1080"
        },
        "InDip": {
          "Borders": "0,0,0,0",
          "Bounds": "1920,0,1536,864",
          "OutsideBounds": "1920,0,1536,864"
        },
        "RealPitch": {
          "X": 0.17916666666666667,
          "Y": 0.17962962962962964
        },
        "PhysicalRatio": {
          "X": 1.0,
          "Y": 1.0
        },
        "Pitch": {
          "X": 0.17916666666666667,
          "Y": 0.17962962962962964
        },
        "OverallBoundsWithoutThisInMm": "-638,0,1238,340",
        "GuiLocation": "0,0,0,0",
        "WinDpiX": 120.0,
        "WinDpiY": 120.0,
        "RawDpi": {
          "X": 141.0,
          "Y": 141.0
        },
        "EffectiveDpi": {
          "X": 120.0,
          "Y": 120.0
        },
        "DpiAwareAngularDpi": {
          "X": 123.0,
          "Y": 123.0
        },
        "WpfToPixelRatio": {
          "X": 1.25,
          "Y": 1.25
        },
        "PixelToDipRatio": {
          "X": 0.8,
          "Y": 0.8
        },
        "PhysicalToPixelRatio": {
          "X": 5.5813953488372094,
          "Y": 5.56701030927835
        },
        "MmToDipRatio": {
          "X": 4.4651162790697674,
          "Y": 4.4536082474226806
        },
        "RealDpi": {
          "X": 141.76744186046511,
          "Y": 141.4020618556701
        },
        "DpiX": {
          "X": 141.76744186046511,
          "Y": 141.4020618556701
        },
        "RealDpiAvg": 141.58486972253624
      }
    ],
    "AutoUpdate": false,
    "PrimaryScreen": {
      "Id": "ACR071C__0",
      "IdResolution": "3840x2160",
      "Primary": true,
      "Orientation": 0,
      "PhysicalRotated": {
        "Borders": "20,20,20,20",
        "Bounds": "0,0,600,340",
        "OutsideBounds": "-20,-20,640,380"
      },
      "InMm": {
        "Borders": "20,20,20,20",
        "Bounds": "0,0,600,340",
        "OutsideBounds": "-20,-20,640,380"
      },
      "InMmUnrotated": {
        "Borders": "20,20,20,20",
        "Bounds": "0,0,600,340",
        "OutsideBounds": "-20,-20,640,380"
      },
      "InPixel": {
        "Borders": "0,0,0,0",
        "Bounds": "0,0,3840,2160",
        "OutsideBounds": "0,0,3840,2160"
      },
      "InDip": {
        "Borders": "0,0,0,0",
        "Bounds": "0,0,1920,1080",
        "OutsideBounds": "0,0,1920,1080"
      },
      "RealPitch": {
        "X": 0.15625,
        "Y": 0.15740740740740741
      },
      "PhysicalRatio": {
        "X": 1.0,
        "Y": 1.0
      },
      "Pitch": {
        "X": 0.15625,
        "Y": 0.15740740740740741
      },
      "OverallBoundsWithoutThisInMm": "-638,0,1622,336",
      "GuiLocation": "0,0,0,0",
      "WinDpiX": 192.0,
      "WinDpiY": 192.0,
      "RawDpi": {
        "X": 162.0,
        "Y": 161.0
      },
      "EffectiveDpi": {
        "X": 192.0,
        "Y": 192.0
      },
      "DpiAwareAngularDpi": {
        "X": 161.0,
        "Y": 160.0
      },
      "WpfToPixelRatio": {
        "X": 2.0,
        "Y": 2.0
      },
      "PixelToDipRatio": {
        "X": 0.5,
        "Y": 0.5
      },
      "PhysicalToPixelRatio": {
        "X": 6.4,
        "Y": 6.3529411764705879
      },
      "MmToDipRatio": {
        "X": 3.2,
        "Y": 3.1764705882352939
      },
      "RealDpi": {
        "X": 162.56,
        "Y": 161.36470588235292
      },
      "DpiX": {
        "X": 162.56,
        "Y": 161.36470588235292
      },
      "RealDpiAvg": 161.96345560727312
    },
    "PhysicalOutsideBounds": "-658,-20,1662,380",
    "PhysicalBounds": "-638,0,1622,340",
    "Enabled": false,
    "LoadAtStartup": false,
    "LoopAllowed": true,
    "LoopX": false,
    "LoopY": false,
    "IsRatio100": false,
    "AdjustPointerAllowed": false,
    "AdjustPointer": false,
    "AdjustSpeedAllowed": false,
    "AdjustSpeed": false,
    "AllowCornerCrossing": false,
    "HomeCinema": false,
    "Pinned": false,
    "ConfigLocation": "0,0,0,0",
    "AllowOverlaps": false,
    "AllowDiscontinuity": false,
    "MaxEffectiveDpiX": 192.0,
    "MaxEffectiveDpiY": 192.0
  },
  "Monitors": [
    {
      "DeviceId": "MONITOR\\ACI27E2\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0012",
      "PnpCode": "ACI27E2",
      "IdMonitor": "ACI27E2_D2LMTF007809",
      "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0012",
      "DeviceString": "Generic PnP Monitor",
      "Devices": [
        {
          "AttachedToDesktop": true,
          "DisplayModes": [],
          "DeviceCaps": {
            "Size": "0,0",
            "Resolution": "0,0",
            "LogPixels": "0,0",
            "Aspect": "0,0",
            "BitsPixel": 0
          },
          "CurrentMode": null,
          "DeviceName": "\\\\.\\DISPLAY4\\Monitor0",
          "DeviceString": "Generic PnP Monitor",
          "State": 3,
          "DeviceId": "MONITOR\\ACI27E2\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0012",
          "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0012"
        }
      ],
      "AttachedDevice": {
        "AttachedToDesktop": true,
        "DisplayModes": [],
        "DeviceCaps": {
          "Size": "0,0",
          "Resolution": "0,0",
          "LogPixels": "0,0",
          "Aspect": "0,0",
          "BitsPixel": 0
        },
        "CurrentMode": null,
        "DeviceName": "\\\\.\\DISPLAY4\\Monitor0",
        "DeviceString": "Generic PnP Monitor",
        "State": 3,
        "DeviceId": "MONITOR\\ACI27E2\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0012",
        "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0012"
      },
      "AttachedDisplay": {
        "AttachedToDesktop": true,
        "DisplayModes": [],
        "DeviceCaps": {
          "Size": "598,336",
          "Resolution": "1920,1080",
          "LogPixels": "192,192",
          "Aspect": "36,36",
          "BitsPixel": 32
        },
        "CurrentMode": {
          "Position": "-1920,0",
          "BitsPerPixel": 32,
          "Pels": "1920,1080",
          "DisplayFlags": 0,
          "DisplayFrequency": 120,
          "DisplayFixedOutput": 0,
          "DisplayOrientation": 0
        },
        "DeviceName": "\\\\.\\DISPLAY4",
        "DeviceString": "NVIDIA GeForce GTX 980 Ti",
        "State": 1,
        "DeviceId": "PCI\\VEN_10DE&DEV_17C8&SUBSYS_115110DE&REV_A1",
        "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Video\\{BFD8B517-417C-11EB-A233-806E6F6E6963}\\0000"
      },
      "MonitorArea": "-1920,0,1920,1080",
      "WorkArea": "-1920,0,1920,1040",
      "HKeyName": "\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Enum\\DISPLAY\\ACI27E2\\9&297bcfdf&0&UID37120\\Device Parameters",
      "AttachedToDesktop": true,
      "Primary": false,
      "Edid": {
        "ProductCode": "27E2",
        "Serial": "00001E81",
        "PhysicalSize": "598,336",
        "ManufacturerCode": "ACI",
        "Model": "ASUS VG278HR",
        "SerialNo": "D2LMTF007809"
      },
      "EffectiveDpi": "96,96",
      "AngularDpi": "81,81",
      "RawDpi": "81,81",
      "ScaleFactor": 1.0,
      "CapabilitiesString": null,
      "MonitorNo": 2
    },
    {
      "DeviceId": "MONITOR\\ACR071C\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0005",
      "PnpCode": "ACR071C",
      "IdMonitor": "ACR071C_",
      "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0005",
      "DeviceString": "XB273K GP",
      "Devices": [
        {
          "AttachedToDesktop": true,
          "DisplayModes": [],
          "DeviceCaps": {
            "Size": "0,0",
            "Resolution": "0,0",
            "LogPixels": "0,0",
            "Aspect": "0,0",
            "BitsPixel": 0
          },
          "CurrentMode": null,
          "DeviceName": "\\\\.\\DISPLAY5\\Monitor0",
          "DeviceString": "XB273K GP",
          "State": 3,
          "DeviceId": "MONITOR\\ACR071C\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0005",
          "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0005"
        }
      ],
      "AttachedDevice": {
        "AttachedToDesktop": true,
        "DisplayModes": [],
        "DeviceCaps": {
          "Size": "0,0",
          "Resolution": "0,0",
          "LogPixels": "0,0",
          "Aspect": "0,0",
          "BitsPixel": 0
        },
        "CurrentMode": null,
        "DeviceName": "\\\\.\\DISPLAY5\\Monitor0",
        "DeviceString": "XB273K GP",
        "State": 3,
        "DeviceId": "MONITOR\\ACR071C\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0005",
        "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0005"
      },
      "AttachedDisplay": {
        "AttachedToDesktop": true,
        "DisplayModes": [],
        "DeviceCaps": {
          "Size": "600,340",
          "Resolution": "3840,2160",
          "LogPixels": "192,192",
          "Aspect": "36,36",
          "BitsPixel": 32
        },
        "CurrentMode": {
          "Position": "0,0",
          "BitsPerPixel": 32,
          "Pels": "3840,2160",
          "DisplayFlags": 0,
          "DisplayFrequency": 144,
          "DisplayFixedOutput": 0,
          "DisplayOrientation": 0
        },
        "DeviceName": "\\\\.\\DISPLAY5",
        "DeviceString": "NVIDIA GeForce GTX 980 Ti",
        "State": 5,
        "DeviceId": "PCI\\VEN_10DE&DEV_17C8&SUBSYS_115110DE&REV_A1",
        "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Video\\{BFD8B517-417C-11EB-A233-806E6F6E6963}\\0001"
      },
      "MonitorArea": "0,0,3840,2160",
      "WorkArea": "0,0,3840,2080",
      "HKeyName": "\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Enum\\DISPLAY\\ACR071C\\9&297bcfdf&0&UID37126\\Device Parameters",
      "AttachedToDesktop": true,
      "Primary": true,
      "Edid": {
        "ProductCode": "071C",
        "Serial": "029154EB",
        "PhysicalSize": "600,340",
        "ManufacturerCode": "ACR",
        "Model": "XB273K GP",
        "SerialNo": ""
      },
      "EffectiveDpi": "192,192",
      "AngularDpi": "161,160",
      "RawDpi": "162,161",
      "ScaleFactor": 1.8,
      "CapabilitiesString": null,
      "MonitorNo": 3
    },
    {
      "DeviceId": "MONITOR\\BOE0747\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0003",
      "PnpCode": "BOE0747",
      "IdMonitor": "BOE0747_0003",
      "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0003",
      "DeviceString": "Generic PnP Monitor",
      "Devices": [
        {
          "AttachedToDesktop": true,
          "DisplayModes": [],
          "DeviceCaps": {
            "Size": "0,0",
            "Resolution": "0,0",
            "LogPixels": "0,0",
            "Aspect": "0,0",
            "BitsPixel": 0
          },
          "CurrentMode": null,
          "DeviceName": "\\\\.\\DISPLAY1\\Monitor0",
          "DeviceString": "Generic PnP Monitor",
          "State": 3,
          "DeviceId": "MONITOR\\BOE0747\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0003",
          "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0003"
        }
      ],
      "AttachedDevice": {
        "AttachedToDesktop": true,
        "DisplayModes": [],
        "DeviceCaps": {
          "Size": "0,0",
          "Resolution": "0,0",
          "LogPixels": "0,0",
          "Aspect": "0,0",
          "BitsPixel": 0
        },
        "CurrentMode": null,
        "DeviceName": "\\\\.\\DISPLAY1\\Monitor0",
        "DeviceString": "Generic PnP Monitor",
        "State": 3,
        "DeviceId": "MONITOR\\BOE0747\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0003",
        "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class\\{4d36e96e-e325-11ce-bfc1-08002be10318}\\0003"
      },
      "AttachedDisplay": {
        "AttachedToDesktop": true,
        "DisplayModes": [],
        "DeviceCaps": {
          "Size": "344,194",
          "Resolution": "1920,1080",
          "LogPixels": "192,192",
          "Aspect": "36,36",
          "BitsPixel": 32
        },
        "CurrentMode": {
          "Position": "3840,0",
          "BitsPerPixel": 32,
          "Pels": "1920,1080",
          "DisplayFlags": 0,
          "DisplayFrequency": 60,
          "DisplayFixedOutput": 0,
          "DisplayOrientation": 0
        },
        "DeviceName": "\\\\.\\DISPLAY1",
        "DeviceString": "Intel(R) UHD Graphics 630",
        "State": 1,
        "DeviceId": "PCI\\VEN_8086&DEV_3E9B&SUBSYS_20001A58&REV_00",
        "DeviceKey": "\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Video\\{1EF10179-418A-11EB-A230-806E6F6E6963}\\0000"
      },
      "MonitorArea": "3840,0,1920,1080",
      "WorkArea": "3840,0,1920,1030",
      "HKeyName": "\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Enum\\DISPLAY\\BOE0747\\4&112da556&0&UID265988\\Device Parameters",
      "AttachedToDesktop": true,
      "Primary": false,
      "Edid": null,
      "EffectiveDpi": "120,120",
      "AngularDpi": "123,123",
      "RawDpi": "141,141",
      "ScaleFactor": 1.0,
      "CapabilitiesString": null,
      "MonitorNo": 1
    }
  ]
}`

**Comment by atticusnari** [comment]
I'm unfortunately having the same issue. Is there any fixes at all?

**Comment by atticusnari** [comment]
I finally found out how to fix it. All you have to do it install this program called [ControlMyMonitor](https://www.nirsoft.net/utils/control_my_monitor.html), select the monitor you're having trouble with and change the variables of "Video Black Level: Green" and "Video Black Level: Blue" to whatever default values you had them originally!

**Comment by DerMaxPower** [comment]
It should just be fixable by resetting your monitor in the OSD of your monitor.
