### ISSUE TITLE
Flagged by malware analysis

### ISSUE THREAD

**Issue by Quinten0508** [mgth/LittleBigMouse#166]
The executable has been flagged by 4 virustotal engines and by crowdstrike falcon: https://www.hybrid-analysis.com/sample/5760b36b506de39cbf8855f3947c57bd742175fed7560023e5d42639ce280d8a. Any idea what's going on?

**Comment by notabot1001** [comment]
6/24/21 - still flagged. This was automatically deleted by my work's security app so I could not install.

**Comment by Quinten0508** [comment]
> If it makes any difference, it was flagged by McAfee

McAfee was also listed in the virustotal report in the original post :)
Either way AV false positives aren't a complete dealbreaker IMO, LittleBigMouse needs to do some manipulation of user input in one way or another. 
* [Virustotal: 2/71 (>3%)](https://www.virustotal.com/gui/file/5760b36b506de39cbf8855f3947c57bd742175fed7560023e5d42639ce280d8a/detection)
* [filescan.io: "no threat"](https://www.filescan.io/reports/5760b36b506de39cbf8855f3947c57bd742175fed7560023e5d42639ce280d8a/8f4fbed0-bd1b-47c7-8348-6f32ad8a178c)
* [JoeSandbox: "suspicious"](https://www.joesandbox.com/analysis/778967/0/html)
* [Hybrid-Analysis: "grayware" or PuP](https://www.hybrid-analysis.com/sample/5760b36b506de39cbf8855f3947c57bd742175fed7560023e5d42639ce280d8a)
	* _MetaDefender 0/22_
	* _CrowdStrike Falcon "no details"_
	* _VirusTotal 2/71_

Closing the issue since the amount of AVs flagging this seems negligible, feel free to re-open when there's actual malicious behavior.

**Comment by Benargee** [comment]
Still
- ❌LittleBigMouse_5.6.0.exe
  - https://www.virustotal.com/gui/file/9d49a6bb109336a037592b3bcca8934ead080a0a16d0670c7608e55100913b18  
- ❌LittleBigMouse_5.5.1.exe
  - https://www.virustotal.com/gui/file/7332ce0bb17f6c95e13ddd91c8db10b2419fca6e7fd3feca8ff8979acef031fd  
- ❌LittleBigMouse_5.5.0.exe
  - https://www.virustotal.com/gui/file/76653085b35355ba489f657fc7fb26802f79ff7f4a1fb111259c1ce4b17ced25  
- ❌LittleBigMouse_5.4.1.exe
  - https://www.virustotal.com/gui/file/d617c545693337084511942974830de697ff0553e8e598ac5d04c969e7f3c0cc  
- ❌LittleBigMouse_5.4.0.exe
  - https://www.virustotal.com/gui/file/32d5e34d15a52bb65e1c8a751e577fdffb985956e654354c617dfb62eaea531d  
- ❌LittleBigMouse_5.3.0.exe
  - https://www.virustotal.com/gui/file/de878c16e4ce9bbe6136e1e460728554069f6c3da002b8726741e8aa8b5fef79  
- ✅ LittleBigMouse-5.2.3.0.exe
  - https://www.virustotal.com/gui/file/99bcde2ebdb72206af313101da41ca58506543925e2536727bb94a1110183508
