### ISSUE TITLE
Not Auto Starting At Load Up

### ISSUE THREAD

**Issue by MartinWithAnI** [mgth/LittleBigMouse#171]
Hi,

This echoes a thread from a couple of days back. Installed, set the relevant setting...doesn't load on log on to Windows. No task in Start-up in Task Manager.

I uninstalled, deleted associated Folders + Registry entries. Rebooted PC. Installed latest version, set up again. Rebooted PC, still does not start automatically.

**Comment by wunaidage** [comment]
I setup LBM on scheduler task on my old PC without any problem. it successfully run at start up. but on my new PC, the task scheduler last run result will be 0xC00041D. according to https://superuser.com/questions/869526/what-does-the-error-message-0xc000041d-mean it is a callback error. looks like we need a patch fix

**Comment by Draxonic** [comment]
+1

**Comment by e30Birdy** [comment]
Same issue here. Tried different software before which also had issues at startup but here I have the same. Just want it to autostart and run when I log on

**Comment by GrotenM** [comment]
Same issue for me.

**Comment by Draxonic** [comment]
I found that if I go into Scheduled Tasks and run it manually once, it works after that (but doesn't load the notification tray icon). I can live with this. Very happy with the result. Honestly, if I was the developer, I'd put this on Steam for a couple of bucks and monetise it.

**Comment by shipitsteven** [comment]
If you're on Windows 10, this fixed it for me:
1. Search `Task Scheduler` in Start menu, open it
2. Click `Task Scheduler Library` on left side bar
3. Find LittleBigMouse in the list, name should be something like `LittleBigMouse_PCname_Username`, and the description for it should be something like _"Multi-dpi aware monitors mouse crossover"_
4. Right click on it, select Properties
5. On the bottom, change `Configure for` (mine was originally on Windows 7, etc.) to Windows 10

Next time you restart your PC the task should run automatically.

**Comment by e30Birdy** [comment]
Cursr.app just does a better job and Software is still being developed. This no one is touching

**Comment by Draxonic** [comment]
> [Cursr](https://cursr.app) does a better job and Software is still being developed. This no one is touching

Cursr still needs some work. It might be good in future, but I went back to LittleBigMouse after using Cursr for 5 minutes and not being able to set pointer continuity across screens with different resolutions.

**Comment by e30Birdy** [comment]
> > [Cursr](https://cursr.app) does a better job and Software is still being developed. This no one is touching
> 
> Cursr still needs some work. It might be good in future, but I went back to LittleBigMouse after using Cursr for 5 minutes and not being able to set pointer continuity across screens with different resolutions.

I have no issues in 1.3.3 and use a 4k and wqhd monitor.

**Comment by mattgallion** [comment]
> 

Cursr's scaling feature requires the pro version.

**Comment by Nyigam** [comment]
Anyone found a solution to the program not running on startup?
