### ISSUE TITLE
Corner crossing isn't working properly

### ISSUE THREAD

**Issue by Zaelium** [mgth/LittleBigMouse#172]
My cursor moves across the screens just fine when I open the program first, but as soon as I make any changes to it and click the start button, it stops working and reverts to windows' original settings. I can then close the program and open it again and it works again.

EDIT:
It now completely stopped working, even if I close and open again, unless I stop the process in the task manager and then run it as an administrator.

**Comment by GameSpate** [comment]
Same issue here. It's unusable if I can't get this to work :/

**Comment by congmingyige** [comment]
+1
