### ISSUE TITLE
Problem with mouse dpi on new monitor.

### ISSUE THREAD

**Issue by Ker2** [mgth/LittleBigMouse#175]
Switched a 60hz 4k monitor for a 144hz 2560x1440 monitor. While on the side I have two 60hz, 1080 monitors, all the same size.

Now when I try and drag my mouse across the monitors it jumps up around when exiting the 1440 monitor and entering the 1080.  This is a new problem because the last monitor, that was 4k, didn't have this problem.  I've tried but I cant find a solution for this, is there a way to make it so that the mouse enter and exit at the same horizontal line while it transits my screens. 

I've tried nvidea DSR with smoothness and it's not working out, the text is borderline unreadable. 

Thank you for whatever help and answers I'll get.

**Comment by 4nqyi** [comment]
Posted some tips in another post. It might help you out. Clear your registry and start again.
https://github.com/mgth/LittleBigMouse/issues/188#issuecomment-1204817313
