### ISSUE TITLE
Publishing new release?

### ISSUE THREAD

**Issue by jucor** [mgth/LittleBigMouse#177]
First of all: thanks *a lot* for this awesome tool. I use it every single day :) Can't believe Win10 doesn't handle this by default. Thanks for your work on this!

And thanks for the updated commits since the last release :) 

Any chance you could provide a precompiled version that includes these latest commits? The last release is from 2019, and you've added some cool bugfixes since then :)

Thanks for considering and for your time!

**Comment by wurlog** [comment]
second that. It's super usefull and having the latest version avaliable would be great :)

Thanks for all the work you put into it.
