### ISSUE TITLE
Game ban caused by LittleBigMouse?

### ISSUE THREAD

**Issue by Warschak** [mgth/LittleBigMouse#179]
Anyone know of any issues when using LittleBigMouse and being banned from certain videogames for it being flagged as "malicious software"? I've just been banned from Destiny 2 and the only software I downloaded in the past two weeks is LittleBigMouse. Could anyone provide any insight as to how LBM could be flagged as malicious and how I can convince the game devs that this software is what got me wrongfully banned?

**Comment by JakobStaudt** [comment]
This is speculation only but maybe the game detects that LBM moves the mouse cursor and thinks you are using an Aimbot or something like that.

**Comment by Leonetienne** [comment]
I have been playing WoW and CoD with lbm for ages and nothing has happened yet. Seems plausible tho... have been wondering aswell..

**Comment by StefanCristian** [comment]
> So please could you add a setting where lbm disables when you run an fullscreen 3d application?

Bit of a stretch. You can create a PS script that does that and it would be less time invested compared to implementing this feature.

**Comment by VinceBT** [comment]
Maybe this is overkill but I made this, I have no knowledge about Powershell: https://github.com/VinceBT/LBMM

**Comment by mgth** [comment]
see #278
