### ISSUE TITLE
Can't detect my third monitor

### ISSUE THREAD

**Issue by marcglasberg** [mgth/LittleBigMouse#181]
I have a 4k Samsung monitor in the center, and 2 smaller full-hd Dell monitors on each side. The 2 dells are exactly the same model. It detects the left Dell and the center Samsung. The monitor on the right is not detected.

**Comment by marc-eggers** [comment]
Check voidptr's comment in this thread. It's not exactly a great fix, and it resets on reboot for me, but if you depend on this software, it seems like it's your only option at the moment.

https://github.com/mgth/LittleBigMouse/issues/80
