### ISSUE TITLE
Mouse sticking in game

### ISSUE THREAD

**Issue by Raggle66** [mgth/LittleBigMouse#184]
So I've had this issue for a while now and have tried everything to try and fix it. 

I've tried different mice, upgraded my CPU, my Motherboard, reinstalled windows, deleted and redownload mouse drivers. Literally everything I could think of. 

The issue is when playing games using Key board and mouse, the left click will randomly stick so you will continue to attack or do what ever left click is assigned to. I then have to press multiple times on left click to get it to stop.  I found out today that this clicking issue I've had for over 12 months was being caused by Little bit mouse.

**Comment by Chevan94** [comment]
Same with me.
Seems to be happening when the mouse reaches the screen border.
Has anyone come up with the fix other than disabling LBM entirely when playing a game?

**Comment by MasterProcrastinator** [comment]
Also here to report it. Seems like a weird bug to have, have there been pull requests fixing it?

**Comment by VinceBT** [comment]
Can you try this ? @Raggle66 @GrotenM @Chevan94 @MasterProcrastinator  https://github.com/VinceBT/LBMM/releases/tag/1.0.0
This is a program that I made specifically for this matter

**Comment by MasterProcrastinator** [comment]
Hey Vince, that's pretty cool and I think i'll end up trying it out if I feel like it's worth the effort, but i'm still left wondering why this program even causes it in the first place and if it's fixable, because if not i'll probably use your solution, drop this software, or come back in a few years to fix it myself if I have the programming knowledge

**Comment by stom66** [comment]
I am also experiencing this issue when playing Deep Rock Galactic.

It is interfering with all actions bound to mouse buttons, not just left/right-click but also actions bound to my thumb buttons.

The issue occurs when using windowed fullscreen / borderless window modes.

Disabling LBM resolves the issue.

Many thanks to Vince for the workaround, but it would be great if it could be fixed without needing to install a third-party solution.

**Comment by MonkeyGoneWIld** [comment]
I was having the same issue, seems like reverting back to version 4.1.6598.15330 resolved the issue for me.

**Comment by mgth** [comment]
see #278
