### ISSUE TITLE
Littlebigmouse no longer working

### ISSUE THREAD

**Issue by UmbraMortem13** [mgth/LittleBigMouse#190]
I'm unsure if this is just an isolated issue or if windows updated and lost compatibility, however Littlebigmouse now refuses to save monitor configuration info, simply resetting custom scaling to default every launch and not starting, instead giving an unhandled exception "cannot write to the registry key". I've been running it for at least a year now on windows 10 with little to no issues, but I noticed after changing my monitor setup (simply horizontal to vertical, 0 hardware changes) it has been refusing to function, even after multiple reinstalls and restarts. I can paste the exception error text if that helps.

**Comment by DaveB1977** [comment]
It's been this way for almost 2 years, author needs to update or stop allowing downloads, used to be brill now it's a pain in the ass.
