### ISSUE TITLE
Glitching with games forcing actions to become toggled.

### ISSUE THREAD

**Issue by main-antagonist** [mgth/LittleBigMouse#195]
Primary monitor is 2k, secondary monitor to the left is 4k, I've adjusted LBM to allow my cursor to travel across both monitors with no issues for normal use however...
Playing the majority of my games I have no issues except some games that run on 'unreal' Ghostwire Tokyo and Gears5
It forces my zoom to become a toggle randomly and for my shooting to become toggled on or not shoot at all.

Testing with Gears5 last night sometimes I could get the aim to glitch and become locked into toggle state after 10 zooms but other times 20+ I usually strafe with WASD when going into zoom which triggers it more often for some reason.

Disabling LBM resolved the issues in my games entirely.

**Comment by permissionBRICK** [comment]
Thank you, this has been driving me insane, and I finally think I narrowed it down to LBM. At least it seems its not just me. What seems to be happening:
The current mouse button states seem to be sporadically getting stuck, not just in games but in Windows as well, either clicks will not register, or they will not release until you click the button again, this happens for left, right and center click so far

**Comment by stom66** [comment]
I am also experiencing this issue when playing Deep Rock Galactic.

It is interfering with all actions bound to mouse buttons, not just left/right-click but also actions bound to my thumb buttons.

The issue occurs when using windowed fullscreen / borderless window modes.

Disabling LBM resolves the issue.

**Comment by MonkeyGoneWIld** [comment]
I was having the same issue, seems like reverting back to version 4.1.6598.15330 resolved the issue for me.
