### ISSUE TITLE
Program Continues to Run After Second Screen is Disconnected.

### ISSUE THREAD

**Issue by Lucien950** [mgth/LittleBigMouse#203]
>Feature Request

I have a large 1080p monitor and a small 4k laptop screen. When I unplug the HDMI from the laptop, the mouse is stuck in the top left quarter of the screen. I can't even reach the taskbar to stop LittleBigMouse, so I have to kill it through task manager.

LittleBigMouse should automatically stop running after all monitors are disconnected (i.e. only one screen left)

**Comment by GarethBlain** [comment]
THis appears to be a dupicate of [On undock mouse is locked in area of laptop (primary) screen #77](https://github.com/mgth/LittleBigMouse/issues/77)
