### ISSUE TITLE
"Start on boot" doesn't work

### ISSUE THREAD

**Issue by Aashishkebab** [mgth/LittleBigMouse#206]
Task won't start on boot. Is anybody still developing this thing? The last release was three years ago.

**Comment by 4nqyi** [comment]
Try this person's solution.
https://www.reddit.com/r/software/comments/v0048p/comment/img7sjj/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by Aashishkebab** [comment]
I did try it. Not only does it not work,  but it glitches out the UI when you open it, and I have to force stop the daemon in Task Manager.

**Comment by Aashishkebab** [comment]
> Try this person's solution. https://www.reddit.com/r/software/comments/v0048p/comment/img7sjj/?utm_source=reddit&utm_medium=web2x&context=3

Actually, there is already a task that the application itself creates to start on boot in the Task Scheduler. It is called "LittleBigMouse_COMPUTER_NAME_username".

**Comment by Aashishkebab** [comment]
The only solution I've found to work is one I created.

Create a batch file with the following:

`start "C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe" "C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe" --start`

Set that to start at login with Task Scheduler.

**Comment by ArdeoDeo** [comment]
For me, it started running with boot after I ran application "as administrator" and then I re-checked "Load at startup" option. (Win 11)
