### ISSUE TITLE
LMB & RMB sometimes not reacting correctly while playing FPS Games

### ISSUE THREAD

**Issue by TWerner02** [mgth/LittleBigMouse#207]
When playing some shooter games (especially in Valorant, but interestingly NOT in CS:GO), the LMB and RMB are not reacting correctly. I don't know if this is a personal issue, but the mouse buttons sometimes get "stuck", that means that they act like I hold them, and sometimes they don't react at all, which ends in me spamming my buttons in hope they will react sometime. I tried a different mouse and it has the same exact issues as my own. After disabling this programm everything works as intended.

Quick edit. My Monitor has 144Hz, maybe thats where the problem is.

**Comment by Gabrycloud** [comment]
I have the IDENTICAL problem. I installed today LittleBigMouse because I've just bought a second monitor and the mouse started acting weird on Valorant. When I closed LittleBigMouse app, everything worked well

**Comment by OmniMutiny** [comment]
Same problem for me. Windows 11, 240hz at 1440p. Maybe an exclude program functionality could be implemented? For now, just a quick disable with hotkey would be amazing.

**Comment by Wubzzz1337** [comment]
I run into the same Issue, hope this could be fixed because this program is a lifesaver :P
