### ISSUE TITLE
Can´t cross borders

### ISSUE THREAD

**Issue by SkillerAmSkillen** [mgth/LittleBigMouse#213]
Whenever I start LBM, it stacks both monitors on top of each other. When I sort them to match my actual displays and apply my changes and start LBM, i can´t cross any borders to another display, neither direction. Horizontal and vertical loops are working, but nothing else.

**Comment by 4nqyi** [comment]
Paste screenshots of your location settings

**Comment by SkillerAmSkillen** [comment]
> Paste screenshots of your location settings

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/41235294/197345667-3904d3b8-e723-41b7-a8b7-29f7057377eb.png">

**Comment by 4nqyi** [comment]
Uncheck these options

Allow overlaps
Allow discontinuity 
Allow cross cornering

if it still doesn’t work clear you registry and start fresh
