### ISSUE TITLE
Program doesn't work for me and I don't know why.

### ISSUE THREAD

**Issue by dominikpin** [mgth/LittleBigMouse#217]
![20221110_225816](https://user-images.githubusercontent.com/99584426/201215144-6ac7fe88-4d6d-488f-8162-80ee32bf1e1d.jpg)
![Screenshot 2022-11-10 225955](https://user-images.githubusercontent.com/99584426/201215164-523d7958-7d58-4d82-af2a-0d329d71f7fa.png)
I think program just doesn't work for me or I don't really understand how to use it. It looks like nothing changes even if I change something and the checkmark to apply changes. It may be because I'm using old TV as a second monitor? Please help

**Comment by dominikpin** [comment]
I also aligned the rulers but nothing seems to work.
![Screenshot 2022-11-10 231510](https://user-images.githubusercontent.com/99584426/201217886-8c0e6237-f38e-4b11-a285-378a6f18f540.png)
![20221110_231451](https://user-images.githubusercontent.com/99584426/201217968-18db852e-69f5-4bc8-98c2-af85a870a135.jpg)

**Comment by 4nqyi** [comment]
What are you trying to achieve and what issue are you running into?
Try scaling the large screen to the same size as the small one.

Dont touch the size settings.

If you have any issues, delete the registry setting and start fresh.
HKEY_CURRENT_USER\SOFTWARE\Mgth\LittleBigMouse
