### ISSUE TITLE
Mouse pointer jumps to middle on same Monitor

### ISSUE THREAD

**Issue by BO45** [mgth/LittleBigMouse#22]
Hi. I tried the tool with 2 monitors (4k and 1080p) but whenever I go to the right of my first monitor the mouse pointer jumps back to the middle of the screen of the first monitor. I haven't been able to figure out how to make it transition to the second monitor.
[These](http://i.imgur.com/Sg7EekO.png) are my settings. Is there perhaps anything incorrectly set?

**Comment by mgth** [comment]
last beta should correct this

Mathieu
