### ISSUE TITLE
Submit this to powertoys

### ISSUE THREAD

**Issue by ntindle** [mgth/LittleBigMouse#220]
This is awesome. It would be great if you contributed to it to power toys  (if possible). It’s the perfect little utility that would fit right in.

**Comment by ntindle** [comment]
https://github.com/microsoft/PowerToys

**Comment by walkur1** [comment]
Agreed!

**Comment by Rap22tor** [comment]
Please do!

**Comment by BrentNewland** [comment]
This project is licensed GPL, PowerToys license is MIT. Can't use GPL code in an MIT licensed project.
