### ISSUE TITLE
Drive settings in vcp control not adjusting.

### ISSUE THREAD

**Issue by shehateschadi** [mgth/LittleBigMouse#224]
the drive settings are all stuck at 0 and i cant change them back, the box that should be green just stays yellow and the drive settings dont reset back to normal even when i reinstall the monitor drivers and littlebigmouse program. 

really need a fix since my second monitor is basically useless now,
the monitor still works like normal when i plug it into another device.

![Screenshot 2022-12-10 173121](https://user-images.githubusercontent.com/120269464/206865091-282bfc71-fcd8-421d-8634-4c2d6d4f9f18.png)

**Comment by KSOL2000** [comment]
I had the same problem. After using "drive" sliders I got awful green tint on one of my external monitors. After that sliding drive sliders had no reaction. And when reopening LBM red and blue sliders were always stuck at 0, no matter what value I left them before closing the program.  Reinstalling LBM or deleting external monitor settings in windows registry didn't help.
What did help was factory reset of external monitor settings in it's menu.

**Comment by mgth** [comment]
Sorry about that, it can append when ddci is not correctly reported, and you choose try anyway, then I have no way to know if drive is supported. As said, it's better to factory reset the monitor.
