### ISSUE TITLE
Can I make a border between two monitors sticky?

### ISSUE THREAD

**Issue by Napster653** [mgth/LittleBigMouse#227]
In the default Windows display tool I can make a slightly bigger gap between two monitors to have a virtual 'stickyness' when moving the border between them. As you can see here, passing the mouse between 1-5 and 2-6 is sticky, but 3-4 is not.

![image](https://user-images.githubusercontent.com/32395467/209818515-2e073f89-4b3c-491b-97cd-dc40debc9d94.png)

I turned to this tool looking for this feature. Is this something that LittleBigMouse can do?

![image](https://user-images.githubusercontent.com/32395467/209818830-9387eb66-f1eb-4328-89ca-ba8b1c4ecd24.png)

I attempted it leaving a space between the two rows of monitors, but it's not making any difference and there no stickyness between any of them.

**Comment by 4nqyi** [comment]
In the location settings adjust all your monitors so they're all aligned. This will scale their DPI so you'll always jump between the same top/bottom monitor. 

![image](https://user-images.githubusercontent.com/11065729/224516726-74f2e2cd-02b3-44fd-8976-bd3a5cf53b50.png)
