### ISSUE TITLE
Please help configure

### ISSUE THREAD

**Issue by HoodedMenace9** [mgth/LittleBigMouse#228]
Not sure if there is a video somewhere on how to configure this, But I heard about this from a friend and have zero clue how to configure it correctly. I have a 27 inch 1440 & 2 24 inch 1080 monitors configured in this way.
![Capture](https://user-images.githubusercontent.com/113478626/210165909-c17b9f9c-9750-47f1-8202-5124eb144ddb.PNG)
![Capture2](https://user-images.githubusercontent.com/113478626/210166145-a880fb4a-1dba-4c78-adab-647921d4232a.PNG)
I tried just checking enable and applying it but all that did was stop my mouse from being able to go to my top monitor. Included this other screen shot just incase.
![image_2023-01-01_011653790](https://user-images.githubusercontent.com/113478626/210166036-4973dc6f-4d8e-4ff8-acfb-473b5d746255.png)

**Comment by 4nqyi** [comment]
start by resetting the registry. then follow the post below.

https://github.com/mgth/LittleBigMouse/issues/212#issuecomment-1280067622

**Comment by setothegreat** [comment]
> start by clearing the LBM registry. **Don't touch the size settings, this causes unpredictable behavior.**
> 
> HKEY_CURRENT_USER\SOFTWARE\Mgth\LittleBigMouse
> 
> This will allow you to seamlessly move the mouse cursor across screens: Align the screen edges to form a rectangle canvas in the _Location_ settings . You can adjust the landscape monitor height depending on where you want your mouse to land on the portrait monitor. I set mine so that the landscape monitors occupy the portrait monitor edge 50/50. You can adjust it to 60/40 or whatever to occupied 100% of the portrait edge.
> 
> ![image](https://user-images.githubusercontent.com/11065729/210282490-fbfa95ea-e79c-457f-94ca-fea32c6c959e.png)
> 
> My screen setup is similar to yours but the vertical monitor is on the left. ![image](https://user-images.githubusercontent.com/11065729/210282796-480d4abb-52e2-46db-a02e-e3eb15c178ff.png)

Hey, just wanted to thank you for the tip regarding registry files, as I had no idea they were located there, and deleting them completely fixed the issue I outlined [here](https://github.com/mgth/LittleBigMouse/issues/226).

**Comment by HoodedMenace9** [comment]
> start by clearing the LBM registry. **Don't touch the size settings, this causes unpredictable behavior.**
> 
> HKEY_CURRENT_USER\SOFTWARE\Mgth\LittleBigMouse
> 
> This will allow you to seamlessly move the mouse cursor across screens: Align the screen edges to form a rectangle canvas in the _Location_ settings . You can adjust the landscape monitor height depending on where you want your mouse to land on the portrait monitor. I set mine so that the landscape monitors occupy the portrait monitor edge 50/50. You can adjust it to 60/40 or whatever to occupied 100% of the portrait edge.
> 
> ![image](https://user-images.githubusercontent.com/11065729/210282490-fbfa95ea-e79c-457f-94ca-fea32c6c959e.png)
> 
> My screen setup is similar to yours but the vertical monitor is on the left. ![image](https://user-images.githubusercontent.com/11065729/210282796-480d4abb-52e2-46db-a02e-e3eb15c178ff.png)

Theres something weird going on.. I cleared out the registry entry, and reset it up. everything is configured correct and the movement from  monitor 1 - monitor 3 is flawless, lines up perfectly. I still cant go straight up to my top monitor, monitor 2. Heres a video 

https://user-images.githubusercontent.com/113478626/210411422-30e04e79-5d65-4ced-8b88-6d0571939a3a.mp4

then just as I was going to send this I opened LBM and this is what I seen. which I remember almost everytime I open it this is what Im met with. 

![wtf](https://user-images.githubusercontent.com/113478626/210411551-00066294-52b8-465b-85fc-5febd0e83efc.PNG)

So that looks like what config is staying even when I change it..

**Comment by HoodedMenace9** [comment]
> @HoodedMenace9
> 
> LBM was designed for DPI scaling and mouse continuity rather than pointer alignment.
> 
> Clear your registry again. Leave "Allow overlaps" unchecked. Adjust your locations settings and try not to overlap your screens. Close the window to save the settings.
> 
> Save your LBM registry to file after you have it working properly.
> 
> Have you tried setting it up like i show below? Your mouse won't get stuck at the edges.
> 
> ![image](https://user-images.githubusercontent.com/11065729/210936169-943c14bc-3d8e-4b66-8c5b-3cbb9b4d3ec5.png)

Im not quite sure how to set it up as shown. when I do so my vertical monitor isnt as tall as the 2 horizontal monitors

**Comment by HoodedMenace9** [comment]
tried.. & same issue
![image_2023-01-07_212004152](https://user-images.githubusercontent.com/113478626/211181699-bf8d71d6-e2ae-4e9a-9004-b533f4e08bdb.png)

**Comment by 4nqyi** [comment]
Adjust the % of the screen so screen1 & screen2 are the same size and aligned at the top edge of screen1.
Adjust the % of screen3 so the top edge is aligned with screen2. 

You will need to drag the screen as you adjust the % so the screens are aligned since the position will move as it changes sizes.
In the end it should resemble the image below.

![image](https://user-images.githubusercontent.com/11065729/211184022-6f87ede0-9a46-475f-b9b7-ee91d4daa808.png)

**Comment by 4nqyi** [comment]
@HoodedMenace9 sorry i cant help with that. I've never encountered the issue myself but have seen multiple reports of pointers not being able to cross into the adjacent screen. However your layout looks good.

You can try disconnecting/reconnecting the monitor by pulling out the video cable, or removing the device and reinstalling.
