### ISSUE TITLE
Mouse pointer stuck in corner of second monitor.

### ISSUE THREAD

**Issue by Krissesen** [mgth/LittleBigMouse#23]
Currently trying to use a 15" 4k monitor and a 22" 1680x1050 monitor side by side. 

When crossing from the 4k main screen over to the 22", the pointer seems to cross at the right place, but ~0.2 sec after this, the pointer instantly moves to the upper left corner of the 22" and stays there. Not possible to move the pointer, but when right-clicking the menu comes up in the spot where the pointer is stuck.

Currently running Windows 10

If it'll work, its exactly what i need! Dont know why Windows doesnt allready have this built in.

**Comment by mgth** [comment]
Hi,
I actually have many troubles with windows 10, especially when using 
more than 100% ratio on one screen.
Is this what you use ?
I will post a new version as soon as I get to understand how setmousepos 
work with different ratios.
Mathieu

**Comment by Krissesen** [comment]
Yes, I'm currently at 250% on the 4k screen and 100% on the 22".

Let me know I can be of assistance in any way (tho i have no experience with C#).

**Comment by mgth** [comment]
Maybe you can try beta 4, I found it working quite well in windows 10 (the pattern section is still very buggy)

**Comment by Krissesen** [comment]
Still have the same problem. As soon as the mouse cross between the screens, it gets stuck in the upper left corner. If it helps at all, current setup:
![img_20150910_130417](https://cloud.githubusercontent.com/assets/10530703/9786740/bcf2ecfe-57bc-11e5-8ac7-f8fbe32c3b24.jpg)

**Comment by mgth** [comment]
Could you please report the values you get for each screen in the layout 
property pane (also pixel size, that I just see do not appear in last 
version) maybe a screen capture for each screen. So I can simulate you 
environment.

thanks for helping.
Mathieu

**Comment by Krissesen** [comment]
I just left on a business trip, and won't be back in office before Tuesday. I'll give you the numbers and screenshots asap.

Bg Kristoffer

**Comment by Krissesen** [comment]
![lbm](https://cloud.githubusercontent.com/assets/10530703/9873135/12385462-5b9e-11e5-8825-c025f08739ca.PNG)
![lbm2](https://cloud.githubusercontent.com/assets/10530703/9873139/174a5aa4-5b9e-11e5-902e-249293e07688.PNG)

**Comment by mgth** [comment]
thank you, I will have a look on this today.

**Comment by mgth** [comment]
You may try Beta5 version. Please uninstall before installing the new version, cause it seams that you where not using latest version.

**Comment by mgth** [comment]
Please also note that allow to jump is buggy in this version and should not be used for now.
This function allows to cross empty areas and is not so useful anyway.

**Comment by mgth** [comment]
Maybe you can try last beta, everything should be OK now. (don't forget 
to uninstall last version)
https://github.com/mgth/LittleBigMouse/releases

**Comment by Krissesen** [comment]
It works! 

Nit-picking: My mouse cursor changed size when pressing apply. It's quite small on the 4k screen, as if the w10 scaling doesn't affect the cursor anymore. Also, the default settings got the resolutions correct, but not the size of the 4k monitor. You've made it really easy to adjust, tho.

Kristoffer

**Comment by mgth** [comment]
Great!
- for the size change, that should only append when Adjust pointer is 
checked. It is only useful when you don't use per window ratio. (as for 
adjust speed I think) can you confirm this ?
- For the size I rely on DDC that seams not to be available on your 4k, 
please, can you tell what the recommended ratio is for that screen in 
the Windows control panel ? more than 100% would mean that windows knows 
it's real DPI and there is a solution for us too.

thank you for the report.
Mathieu

**Comment by Krissesen** [comment]
Yep, it was the "Adjust pointer" option that made it small. Works perfect without it. The windows recomended ratio is 250% on the 4k monitor.

BR
Kristoffer

**Comment by mgth** [comment]
ok, thank you for the feedback, I'll see if I can find alternate way to 
retrieve physical size.
please do not hesitate to report bad behaviours.

Mathieu
