### ISSUE TITLE
Windows don't resize/Aren't affected

### ISSUE THREAD

**Issue by Meta-Cake** [mgth/LittleBigMouse#230]
I was originally running this on windows 10 and it worked perfectly for months, but I finally moved over to windows 11 and it was still working fine until I had to reinstall windows for an unrelated issue, I downloaded a little big mouse and suddenly it was only affecting my mouse, works pretty good for that, but all of my windows are still getting the scaling issues where some of the windows will be halfway down the other display.  More documentation integrated into the software itself would be great since it took hours to figure out why I wasn't able to put in my actual monitor sizes and it would just change the width whenever I would put in the height or vice versa.

**Comment by Mik027** [comment]
Same issue.
Win11 22H2

**Comment by mikulik86** [comment]
How did you solve the window scaling issue?
