### ISSUE TITLE
Not working at all windows 10

### ISSUE THREAD

**Issue by ICantGame** [mgth/LittleBigMouse#231]
Another LBM not working thread. Two monitors, 32inch 1080p main then a 24inch 1080p monitor portrait orientation on the right side. Due to dpi differences, the mouse does not evenly transfer from primary to secondary. Tried LBM to fix it, makes no difference, uninstalled and reinstalled, nope. Deleted the registries as recommended, still no. I really am struggling here, I know this was abandoned back in 2019, but any advice would be appreciated.

**Comment by 4nqyi** [comment]
Post a screenshot of your settings.
