### ISSUE TITLE
4 Monitor Multi-Refresh/Resolution detection failure.

### ISSUE THREAD

**Issue by txmxthy** [mgth/LittleBigMouse#232]
Heya,
Might be a bit of an edge case but I have 4 displays, 3 1080p (280hz/144hz/60hz), 1 1440p (165hz), and at any one time only 3 are detected.

With all four enabled the software generally doesnt detect the 280hz even if it is set to 60hz. I've tried setting all the displays to 1080p 60 and for some reason it still wont detect it.

**Comment by 4nqyi** [comment]
Drag your monitors around in the locations settings. I've read that when a monitor is missing it's actually hidden behind another monitor.
