### ISSUE TITLE
Win32 ? ?

### ISSUE THREAD

**Issue by xXcynisterXx** [mgth/LittleBigMouse#233]
I was really interested in this, but MS Defender shows a **Win32/Keygen** and VirusTotal shows **Win32 Malicious** file as well. 
I know some things can have a false positive and I have read a lot of the comments on here but haven't found anything with this.
Has anyone else scanned the file to see this?

Link of the file at [[VirusTotal](https://www.virustotal.com/gui/file/5760b36b506de39cbf8855f3947c57bd742175fed7560023e5d42639ce280d8a)]

Thanks for any advise / clearing this up.
**-Cyn**

**Comment by BrentNewland** [comment]
The only detection on that link right now is "CrowdStrike Falcon". Some no-name company, clearly a false positive.
