### ISSUE TITLE
Mixing up monitors

### ISSUE THREAD

**Issue by MasterSord22** [mgth/LittleBigMouse#238]
For some reason, the program seems to be misidentifying each monitor in some way but not completely, and I have no idea why or how I could fix it. In the first screenshot, the way it looks is about how it should be, but each display, at the top left, says '\\.\DISPLAY_\Monitor0' with the _ being different from the second screenshot, and whatever specs it seems to think it has is lining up between whatever is in the _ and the monitor with the same number in the second screenshot, which is from nvidia control panel. 
It's completely messing with the alignment of all the monitors, and unless there is a way properly assign each monitor, or a way to change the dpi of each display in LBM, the most I could do is eyeball with percentages which I would obviously rather not be the solution I take.
![image](https://user-images.githubusercontent.com/127074055/223022836-52edb997-5ae3-4a2f-beb4-c84ac45b2772.png)
![image](https://user-images.githubusercontent.com/127074055/223021395-f5b403c6-7164-42f4-ab86-8002ed3f3a13.png)

**Comment by 4nqyi** [comment]
in the locations settings drag your monitors to the correct positions. 
https://github.com/mgth/LittleBigMouse/issues/228#issuecomment-1374730017

**Comment by MasterSord22** [comment]
> in the locations settings drag your monitors to the correct positions. [#228 (comment)](https://github.com/mgth/LittleBigMouse/issues/228#issuecomment-1374730017)

The problem is that the sizes and DPI are completely wrong for all the monitors, so even after correcting the pixel sizes, the alignments are all off since, for example, monitor 1 in the first screenshot would take the place of monitor 3 in the second screenshot, and the mouse transitions to all the wrong places
![image](https://user-images.githubusercontent.com/127074055/223632318-4bbb5aaa-7f0a-47e1-aa9b-879b296af67e.png)

**Comment by 4nqyi** [comment]
DPI is arbitrary and is scaled to the dimensions you set your monitors to.

Start by killing LBM then clearing the LBM registry. Don't touch the size settings, this causes unpredictable behavior.
`HKEY_CURRENT_USER\SOFTWARE\Mgth\LittleBigMouse
`

Start LBM and drag your monitors in the locations settings to where you want them.
Do you want them staggered like that? I suggest you align them so you're only dragging your mouse across screen horizontally and not diagonally. In the end it doesn't matter what the dimensions are as long as your monitor edges are aligned to form a rectangle canvas your mouse wont get stuck when crossing screens.

![image](https://user-images.githubusercontent.com/11065729/224516326-d7a2fc53-9386-4cc7-a0ec-c9e44b82c3a6.png)
