### ISSUE TITLE
LittleBigMouse doesn't launch anymore

### ISSUE THREAD

**Issue by JasonMendoza2008** [mgth/LittleBigMouse#239]
I'm using Windows 11 and I've been using LittleBigMouse for years now, but it doesn't work anymore. It just doesn't run. Well, it appears in my task manager, but there's literally nothing else. I suspect it's due to a Windows 11 update? The last update that was installed on my computer is the following: `2023-03 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5023706)`.

I don't know how else I could describe the problem?

I have tried rebooting my PC several times. I have tried uninstalling LittleBigMouse and re-installing it.

**Comment by JasonMendoza2008** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/56092290/225759600-479d66be-33d9-4ed3-9d41-5f1f13403125.png">

**Comment by KNP54** [comment]
I'm having the exact same issue, but on Windows 10 after installing the 2023-03 Cumulative Update for Windows 10 Version 22H2 for x64-based Systems (KB5023696)

**Comment by JasonMendoza2008** [comment]
I guess we identified the cause then.

**Comment by KNP54** [comment]
I'm not sure anymore, I also installed the Optional driver update "Acer Monitor" at the same time. I uninstalled the cumulative update but the problem still persists.. I'll try a rollback for the acer monitor driver.

**Comment by WiseNoobCrusher** [comment]
I am having the exact same issue. It would launch after a little while, but the settings won't save at all after clicking "x" and the daemon doesn't respond at all. Reinstalling doesn't fix it, I also have installed the 2023-03 Cumulative Update for Windows 10 Version 22H2 for x64-based Systems (KB5023696). I also see was Jason sees in Task Manager.

**Comment by KNP54** [comment]
The Acer monitor driver rollback didn't work either... I suspect the cumulative update screwed it up and I can't seem to unscrew it!

**Comment by LastElf** [comment]
I think the latest Win11 update changed how multi-monitor works in some edge cases. I have a 4k next to a 1080 and if I move my mouse in the "dead zone" from one to another, before it would be blocked, now it moves into the other screen. Looks like some kind of one way alignment which overrules some of the hooks LBM uses.

**Comment by JasonMendoza2008** [comment]
Such a nightmare, my 4k screen is so much bigger according to windows but it's literally twice as small ...

**Comment by Aashishkebab** [comment]
It's weird because I JUST got the same issue after installing the latest Windows update (or rather, it installing itself).

In fact, it's causing all sorts of issues with mouse freezes/glitches, issues with OBS recording, and LittleBigMouse not launching at all or working.

**Comment by Aashishkebab** [comment]
@LastElf 
> now it moves into the other screen

I wish, my mouse problems are still there and gaps cause the mouse not to transition between screens.
![image](https://user-images.githubusercontent.com/25588487/225785220-745b0bfe-4e3b-4385-9bfa-dca07e51b1dd.png)

**Comment by DuoClip** [comment]
I have the same issue on the same Windows 11 update done today. After force-quitting the program many times (it wasn't responding) and re-launching it, for some unknown and totally random reason, it started working again. I'm quite sure it will stop working as soon as I reboot the PC but this shows that if you REALLY need it to work you can take 5-10 minutes trying to make it work.

For those who really need it I noticed that when it worked the application didn't open normally, it was hidden in the notification tray from where I Left-Clicked it to open the window itself. When the window opened the mouse started lagging for a few seconds, then it stopped and repeated that cycle of lag 2 or 3 more times. Finally it started working without even needing to click the play button. If you notice this behaviour it might start working for you too but there's no reliable process to get to that point and even if you do it's not guaranteed that it starts working.

**Comment by CodingSquirrel** [comment]
I'll add my voice that I started getting issues with mine today as well. I was getting mouse stuttering every few seconds that made it almost impossible to navigate. Terminating the process fixed the stuttering. I haven't been able to get it to run properly since, even with reinstalling.

**Comment by WiseNoobCrusher** [comment]
I'm hoping this gets fixed :/

**Comment by ben-yeung** [comment]
Writing to add a voice to this. Also had a Win10 update recently and now noticed that LBM does not open. The first time around I had tried to launch it multiple times, and after 10 minutes I would get a bunch of LBM instances finally open but without button functionality.

**Comment by JasonMendoza2008** [comment]
I don't know what changed, but it knows work again.

**Comment by CodingSquirrel** [comment]
> I don't know what changed, but it knows work again.

Thanks for posting this. After seeing your comment I tried it and it's working for me now as well. Still works after restart too.

**Comment by KNP54** [comment]
Yeah it works! But how?!?! No windows update, no software update, no reboot? How is this possible?

**Comment by WiseNoobCrusher** [comment]
Wow, reinstalled it after reading what you guys are saying now and what?? It just works now lol. Even after restart. Did the update just break current installations and any further ones for a small time??? I am confused lol. Tho as this seems like the most random bug, closing this would not be wise for the time being.

**Comment by JasonMendoza2008** [comment]
I honestly did not expect so many people would be in the same situation as me when it first started to bug and when it magically start working again, but I'm happy I'm not the only one confused about it all.

**Comment by Aashishkebab** [comment]
Same thing with me, magically started working again.

**Comment by 4nqyi** [comment]
> @LastElf
> 
> > now it moves into the other screen
> 
> I wish, my mouse problems are still there and gaps cause the mouse not to transition between screens. ![image](https://user-images.githubusercontent.com/25588487/225785220-745b0bfe-4e3b-4385-9bfa-dca07e51b1dd.png)

You’re not setting it up correctly. Think of your screens as Tetris blocks. You want to build a canvas without gaps. 

See this thread I try to walk a user through the configs. https://github.com/mgth/LittleBigMouse/issues/228#issuecomment-1369249039

**Comment by BruhIdkTbh** [comment]
Still doesnt work for me any help?

**Comment by KNP54** [comment]
Just did the windows 11 update. LBM would not start on it's own. Had to kill both LBM processes and relaunch LBM, right-click the icon in the system tray and press start and now it works.
