### ISSUE TITLE
Screen DPI Issues

### ISSUE THREAD

**Issue by Konk5588** [mgth/LittleBigMouse#246]
Having issues getting LBM to load and save the settings I program it for a new desk setup. The mouse positions are way off and won't save to the settings I configure even if they are lined up on the ruler. The mouse jumps half way up the screen when transitioning to the other screen like the windows resolution is taking seniority and not allowing LBM to work. Below are my system specs and windows settings are taking priority, so its jumping like the windows resolution versus the LittleBigMouse setup.

![System Specs](https://user-images.githubusercontent.com/131421509/233528039-25b97cc2-420b-4a4c-9ae4-8c33d238ca62.png)
![LBM](https://user-images.githubusercontent.com/131421509/233528349-3da0b4b8-804e-4888-ac04-da9a9dbe5698.png)
![Windows Settings](https://user-images.githubusercontent.com/131421509/233528557-60dc0ced-aec2-40c8-8855-aedf00910685.png)

Any assistance is appreciated, hoping it is something simple I am missing.

**Comment by Konk5588** [comment]
Update: Everytime I close and reload the program it is defaulting to the original windows setup. Photo Attached.
![Default LBM](https://user-images.githubusercontent.com/131421509/233532148-bb66f1f5-24d0-46a3-ba51-5c0f7a2c8116.png)

**Comment by 4nqyi** [comment]
Compare your registry after making the changes then save your registry to file. If it happens again reload your custom registry settings.
