### ISSUE TITLE
Issues switching between docked environments

### ISSUE THREAD

**Issue by hjordanh** [mgth/LittleBigMouse#247]
I have 3 monitors at home but 2 at the office. When I switch to my USB-C dock at the office, I lose access to 1/2 of one screen (the one with the start menu!) where the mouse just stops. Is this tool intended to be aware of different setups and alternate, or can it be?

**Comment by hjordanh** [comment]
FYI this tool is (otherwise) great and something I'm surprised Windows is missing. You've elegantly solved a problem that is otherwise impossible for anyone (other than Microsoft) to address. Thank you!

**Comment by 4nqyi** [comment]
Unfortunately LBM doesn’t switch between environments. Best bet is to save the registry for each environment and write a script that will switch between registries.
