### ISSUE TITLE
I click start and it loads but nothing actually happens 

### ISSUE THREAD

**Issue by BryanJones2000** [mgth/LittleBigMouse#248]
Ive tried multiple versions but every time I click the start itll load the (cursor loading icon) but then do nothing Tried multiple versions and running as admin any help?

**Comment by 4nqyi** [comment]
What are you expecting to happen? Does the tray icon show Does it show up in your processes?

**Comment by BryanJones2000** [comment]
When I had it before it would Atleast show in tray along with allowing to click the stop button to end program but seems like I can’t even click the play button to get it running anymore

**Comment by rsapgh** [comment]
any fix?

**Comment by VocanicZ** [comment]
same problem with fresh installed window-10

**Comment by BryanJones2000** [comment]
@rsapgh yes I had to go through and wipe all remnants of the app and clear recycle bin and do a fresh install of a different version and it started working for me again
