### ISSUE TITLE
Cannot use minimize feature without having incorrect monitor position

### ISSUE THREAD

**Issue by peot1** [mgth/LittleBigMouse#249]
![image](https://github.com/mgth/LittleBigMouse/assets/139407934/f7005530-f597-405d-86f1-51fcc12fd3fc)

this is how my monitors are positioned - and the mouse does not jump across the screen anymore, which is great

however, i cannot minimize all programs by hitting the button in the bottom right corner of my primary monitor anymore, it just drags over to the second monitor

![image](https://github.com/mgth/LittleBigMouse/assets/139407934/3a145bef-c3f8-49d2-8fbc-806686196cac)

i dislike using windows + d, i prefer hitting the button

i've tried solving this by messing with the position of the monitors so the second one is higher, even though it's lower in reality, so this of course makes the cursor jump again

i would appreciate it if i could just block the bottom right corner of my primary monitor from being able to go to my second monitor

![image](https://github.com/mgth/LittleBigMouse/assets/139407934/8c0b0a7f-2df2-40b6-ab80-743e2d3b59e5)

also, i cannot edit any of these values manually for some reason

![image](https://github.com/mgth/LittleBigMouse/assets/139407934/1e243a4a-5389-47a5-b5da-fa3bd2127193)

**Comment by GreenySA** [comment]
Have a similar problem here, if I minimise the program it goes from this:
![image](https://github.com/mgth/LittleBigMouse/assets/140875190/1881e30e-5a98-46af-9d49-c83ad40ed9c2)
To this:
![image](https://github.com/mgth/LittleBigMouse/assets/140875190/bb442443-a0e9-4025-bbea-1e11226a4c9a)
It also launches in the bottom config on start up.
