### ISSUE TITLE
Basic wiki docs?

### ISSUE THREAD

**Issue by ThreeScreenStudios** [mgth/LittleBigMouse#25]
Hi,

Love the idea of this app, have been looking for something similar for a long time. I gave it a try, and am not sure exactly how to match up my monitors in the way that I'd like. I was wondering, would it be possible to include a basic how to/getting started tutorial?

Let me know if I can help in any way!

**Comment by mgth** [comment]
Well, I have that on the todo list but will not be soon.

Let me know what you don't understand. And feel free to tell be about ergonomie, I'm aware it's not that good.
