### ISSUE TITLE
LittleBigMouse Causing Issues with Valorant

### ISSUE THREAD

**Issue by SpaceFlier100** [mgth/LittleBigMouse#255]
When using LittleBigMouse the mouse will seize up either not clicking, or holding down either right or left click. while in the game. A lot of other users have the same problem, outlined [here](https://www.reddit.com/r/VALORANT/comments/11dvjb6/psa_little_big_mouse_will_screw_with_your_mouse/?rdt=44270&onetap_auto=true).

**Comment by milannanda** [comment]
I am able to replicate this issue in multiple games including Valorant. The common factor between the multiple games is that they are all Unreal Engine titles. See below list

- Valorant
- Fortnite
- Gears 5
- Splitgate
- Crab Champions

Games that I have **NOT** experienced this issue with include
- Halo Infinite
- Halo MCC
- CS2
- Starfield
- Doom Eternal
