### ISSUE TITLE
Monitor gets moved to a different position after saving the config.

### ISSUE THREAD

**Issue by jSydorowicz21** [mgth/LittleBigMouse#257]
I've been running into a bug where my monitor 1 gets moved into a different position after I hit run / apply. This translates into not being able to access that monitor because the software moves it behind my primary monitor. Just installed for the first time, monitor 1 is to the right of 3 when I hit save. I've attached a photo of what happens after hitting run / apply and restarting the program.
![Screenshot](https://github.com/mgth/LittleBigMouse/assets/90705257/b48fbe52-e222-4b07-a206-1b5c27398033)

**Comment by HeadOfMetal** [comment]
This same thing is happening to me as well

**Comment by mgth** [comment]
please test v5
