### ISSUE TITLE
Not detecting Ultrawide Aspect on a vertical monitor

### ISSUE THREAD

**Issue by da3dsoul** [mgth/LittleBigMouse#258]
Images at the bottom that I thought would help. I have 2 ultrawides from Acer, one is my horizontal and one is vertical. The position in Windows is about how they are aligned. I just wiped the config for LBM, so it's not positioned.

LBM isn't working as expected, and I'm guessing it's because it's showing the vertical monitor as a 16:9 (technically 9:16, because vertical). One thing that stood out to me was that the Display Capabilities listed in Info showed 340,600, instead of 284,673 like I'd expect from the EDID. The size is also wrong, as it shows 27.2". It's 28.75", going by the EDID value and the pythagorean theorem, and the 28.75" value seems right from an eyeball with a tape measure.
Any ideas on how to override that, or what the issue and solution might be?

![image](https://github.com/mgth/LittleBigMouse/assets/5205810/14eb9ea2-b5c0-4f40-972c-1c1d52da8d12)
![image](https://github.com/mgth/LittleBigMouse/assets/5205810/7faa7f17-646a-4221-a0a2-a722ac737c15)
![image](https://github.com/mgth/LittleBigMouse/assets/5205810/abbc548c-e9bb-43e1-b1f5-9564800c27ff)

**Comment by mgth** [comment]
You might want to change physical size by hand in the size menu

**Comment by 4nqyi** [comment]
aspect ratio doesnt matter. WYSIWYG so change your screen dimensions to how you want your mouse to behave in the locations screen.

**Comment by da3dsoul** [comment]
I suppose in my setup, that is true. If I was using a grid setup, I think it would.
