### ISSUE TITLE
Stop cursor at monitor edge

### ISSUE THREAD

**Issue by BaileyFurrow** [mgth/LittleBigMouse#260]
This is similar to the #250 feature request to catch the cursor at the monitor corner. For reference, I have a 27" 4K monitor as my main with a 24" FHD monitor to the left. Below is a screenshot of my config.

![image](https://github.com/mgth/LittleBigMouse/assets/66973680/8eac420c-5660-48d0-ba32-c834e55d57a0)

Currently, when I put my cursor towards the bottom left edge of the main monitor, the cursor is placed on the left monitor on the right edge in the vertical center of the screen.

Below is a screen recording of the usual cursor movement (the monitors are not lined up in the recording, but they are aligned and calibrated correctly) followed by the behavior described above.

![2023-10-15_183448](https://github.com/mgth/LittleBigMouse/assets/66973680/d5d26740-e758-4d86-987e-4c1f3735f31a)

I'm not sure if this is a designed feature in LBM or a bug. Because of this, I'm not sure if this should be labeled as a feature request or a bug issue.

What I would like for it to do is when I move my cursor to that bottom left edge, I want the cursor to simply stop as though the cursor reached the end of the screen. It will make mouse movement a little less disorienting when working in that part of the screen.

**Comment by mgth** [comment]
It should work the way you said. Maybe try new V5 with strait algo.

**Comment by OsuCelsius** [comment]
I have 3 monitors and this same issue only happen when moving the cursor from one 2k monitors to other of the same resolution, I don't have any problems moving from any of the two 2k monitors to the 1080.
I think maybe the windows config has something to do with it
(vertical one is 1080, the others are 2k, but the bottom one is much smaller)
![123](https://github.com/mgth/LittleBigMouse/assets/53451135/2863fbca-6d63-43a9-8ec0-9fc364959df2)
