### ISSUE TITLE
[Feature] Auto-disable LBM when monitor config doesn't match the active monitors and auto-reenable when the config does match again

### ISSUE THREAD

**Issue by ChristopherHaws** [mgth/LittleBigMouse#264]
### Feature Request

**Context**: I use LBM because I use 3 monitors with vastly different DPI. I frequently use remote desktop applications like Moonlight/Sunshine, Parsec, and RDP to access my computer remotely which automatically turns off two or all of my monitors when I connect and reenables them when I disconnect.

**Problem**: When remoting into my PC, which disables two of the three monitors in Windows, LBM doesn't automatically detect this change, leading to erratic mouse behavior. Manually stopping LBM resolves this, but then I usually forget to turn it back on.

**Proposed Feature**: Implement an auto-disable/reenable feature in LBM. When the monitor configuration does not match the predefined setup (e.g., when remoted in and monitors are disabled), LBM should automatically disable itself. Once the original monitor configuration is restored (after disconnecting from the remote session), LBM should auto-reenable.

This feature would greatly enhance the usability of LBM for users who frequently switch between remote and local access, ensuring smoother transitions and less manual configuration.

### Additional Information
- **Applications Used**: Moonlight/Sunshine, Parsec, RDP
- **Monitors**: 3 with varied DPI settings

Thanks for this amazing app! :)

**Comment by mgth** [comment]
Done in 5.0.4.1
