### ISSUE TITLE
registry key not exist error?

### ISSUE THREAD

**Issue by EB-Plum** [mgth/LittleBigMouse#269]
release v5.0.2 not worked on my pc. 
despite no error message shown, it had no response. 
no windows, no context menus, just a tray icon.

so I tried to run from source and faced the error from the start.

![image](https://github.com/mgth/LittleBigMouse/assets/32756410/3d2fd298-9038-4d93-82ef-a18ef799903c)

is this error means registry key is missing?  
I'm totally noob for c# project. 

what step may I missed?
or is there a better way to report my error?

**Comment by EB-Plum** [comment]
Look through the registry. as the key is from some path like `Registry.LocalMachine.OpenSubKey(@"SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Connectivity");`
and I can confirm that there are keys in that path.
![image](https://github.com/mgth/LittleBigMouse/assets/32756410/8cb3500e-a8f0-401f-924e-c66ad22e3688)

**Comment by mgth** [comment]
Ok, thank you, this error is there because it does not find your 2nd monitor in first place. I will fix that so you can try again.

**Comment by EB-Plum** [comment]
thank you for quick fix! it starts without error now.

while doing some testing, I think I found some bugs.
like state of 'Apply/Start' is somehow reversed, or while changing size of monitor inner height to 0 triggering UI breaks.  
I will report these issue separately if I found more detail tomorrow.

**Comment by EB-Plum** [comment]
never mind. it works just fine. I think it was a temporary error.
