### ISSUE TITLE
5.0.3 LittleBigMouse does not launch at all

### ISSUE THREAD

**Issue by DxNeXtGen** [mgth/LittleBigMouse#274]
I've uninstalled, reinstalled, restarted my pc, repeated. 

DxDiag included for your convenience. The system tray icon is blank, no UI is launched when program is ran.
[DxDiag.txt](https://github.com/mgth/LittleBigMouse/files/13574813/DxDiag.txt)

I have installed the .NET Framework as prompted, and have gone back to try older versions and am having the same issues,

**Comment by agerberoff** [comment]
Same thing happened to me. I even installed the 4…. Version and nothing happened. Hopefully they fix it soon. Thank you!

**Comment by Queenofchaos** [comment]
I have windows 10 and 11 and tried the programs on both and nothing is working. Just pops up as a black box bottom right corner.

**Comment by RealmX1** [comment]
SAME ISSUE. The program will appear very briefly in task manager, and then disappear when I try to launch it, no visible window is shown.

**Comment by mgth** [comment]
@RealmX1 Still with 5.0.4.1 ?

**Comment by hydroGuo** [comment]
> @RealmX1 Still with 5.0.4.1 ?

I have tried 5.0.4.1 and previous version both have same issue even if I setup necessary components.

**Comment by RealmX1** [comment]
> @RealmX1 Still with 5.0.4.1 ?

Yes. Tried multiple version, including 5.0.4.1.
As I've described. the program appears very briefly in task manager before disappearing, and no window is opened.

**Comment by RealmX1** [comment]
I've currently resorted to
rendering all monitors according to their size with respect to the size & resolution of one specific monitor. 
For example, I have a 2k monitor of 27 inch in size; I'm rendering my 24 inch 1080p monitor at 2560/27*24 =2250 (*1227) so that mouse movement is scaled correctly... which makes the monitor look weird

**Comment by cicklolwut** [comment]
Same issue here, however the app persists in Task Manager under Background Processes.

**Comment by RichardYocke** [comment]
I also have the same issue on a completely fresh install of windows 11

**Comment by DawsonBodenhamer** [comment]
same issue here, I downloaded version 5.0.5.0 (windows 11 PC) and .NET (as prompted) but LittleBigMouse doesn't run at all, even if I right click it from search bar and click "Run as Admin"

**Comment by agerberoff** [comment]
How do we know this isn’t a real software and it’s just a virus!?On Dec 27, 2023, at 11:14 AM, DawsonBodenhamer ***@***.***> wrote:﻿
same issue here, I downloaded version 5.0.5.0 (windows 11 PC) and .NET (as prompted) but LittleBigMouse doesn't run at all, even if I right click it from search bar and click "Run as Admin"

**Comment by Cloudyyy1** [comment]
Same issue
Did anyone find a fix?

**Comment by DxNeXtGen** [comment]
> How do we know this isn’t a real software and it’s just a virus!?On Dec 27, 2023, at 11:14 AM, DawsonBodenhamer ***@***.***> wrote:﻿ same issue here, I downloaded version 5.0.5.0 (windows 11 PC) and .NET (as prompted) but LittleBigMouse doesn't run at all, even if I right click it from search bar and click "Run as Admin" —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

you can literally look at the code

**Comment by lkyu-ly** [comment]
> How do we know this isn’t a real software and it’s just a virus!?On Dec 27, 2023, at 11:14 AM, DawsonBodenhamer ***@***.***> wrote:﻿ same issue here, I downloaded version 5.0.5.0 (windows 11 PC) and .NET (as prompted) but LittleBigMouse doesn't run at all, even if I right click it from search bar and click "Run as Admin" —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

stop using it, so that you won't have any anxiety :(

**Comment by lkyu-ly** [comment]
I tried repeatedly, unintalling and using the just lower version, and at last v5.0.1.0 works on my win11(23H2) device!
But something not so perfect is that the application cant display its text normally when windows is using a dark theme(mode).
Anyway it works. Hope this method could work on you devices.

**Comment by Cloudyyy1** [comment]
> I tried repeatedly, unintalling and using the just lower version, and at last v5.0.1.0 works on my win11(23H2) device! But something not so perfect is that the application cant display its text normally when windows is using a dark theme(mode). Anyway it works. Hope this method could work on you devices.

Cheers
White mode fix it

**Comment by Piperci** [comment]
> I've uninstalled, reinstalled, restarted my pc, repeated.
> 
> DxDiag included for your convenience. The system tray icon is blank, no UI is launched when program is ran. [DxDiag.txt](https://github.com/mgth/LittleBigMouse/files/13574813/DxDiag.txt)
> 
> I have installed the .NET Framework as prompted, and have gone back to try older versions and am having the same issues,

So I just installed LBM 5.05 on both my home PC and work PC (both Win10).  Home PC works with no problems.  
Work PC I get the same behavior as OP.  LBM shortcut has the blue/yellow shield on it.  Starting LBM gives me the yellow UAC unknown publisher warning.  It tries to start, LBM.Ui.Avalonia shows running in Task Manager. There's a blank spot in the taskbar notification area where the icon should be but hovering over it gives you nothing, neither do left/right clicks.   

My guess is my IT dept is blocking some aspect that it needs to run.  🤷‍♂️

**Comment by FliesEyes** [comment]
I am not having any success myself yet.  I had it working on a previous PC.  I suppose I will just need to watch this forum to see if any updates or advice as to installation requirements are posted.

**Comment by Piperci** [comment]
FWIW I ran across this response on a similar thread.  

_Originally posted by @bevellon in https://github.com/mgth/LittleBigMouse/issues/307#issuecomment-1935490835_
              _The problem is that the program requires admin credentials or UAC prompt to run. If enabled for startup it will not run for a regular user. I have an admin account separate from my main account. The default task scheduler config is to run on admin login. I tried to change this to run at startup for all users, but had the same issue where it will run in the background without doing anything. The program runs as expected with admin login, no intervention needed. I also tried to change the manifest to run as invoker on my main account, but again the program would run and not do anything._

**Comment by jgrafman** [comment]
Same issue for me. Sucks, I was hoping this would be a nice fix

**Comment by PaulSorauer-IPG** [comment]
Great news! [Version 5.2.2.0](https://github.com/mgth/LittleBigMouse/releases/tag/v5.2.2) has been released and I am now running LBM successfully! Yay!
