### ISSUE TITLE
New user - Adjust Pointer Checkbox and a few other bugs

### ISSUE THREAD

**Issue by ajhalls** [mgth/LittleBigMouse#28]
First off let me say a HUGE THANK YOU! I have spent the last 3 days trying to develop my own version of this before finding your solution. I think I may have even found it early on, but when you go to the main page it doesn't mention that you have the precompiled releases and not being a C developer was discouraged from trying.

That being said, I did find it, and the releases and it solved my problem, but not without noticing a couple bugs.

When I opened the app, I adjusted the positions, then clicked to show ruler. I didn't realize at first I could reposition the ruler on all 3 monitors separately and so was trying to change the location of the right monitor so the rulers would match up. Repositioning the right monitor after hiding rulers would crash the program.

I then got everything setup correctly, but the checkboxes for Adjust Pointer and adjust speed are disabled. I am able to click everything else but those. I am not sure if that is just a cosmetic thing and it really is working in the background or something. 

I tried applying it and starting it, but nothing changed, luckily I decided to reboot with the "Load at Startup" enabled and it started working. It was interesting because it seemed to get more accurate the more times I crossed the monitor barrier, or it was still processing calculations and the timing just happened to correlate.

If I could, I would totally fork this and work on it with you, but I am only a javascript guy, so for now I will just make a few comments for quick and easy cosmetic things that should be quick.

Barring a help file, it would be nice to have some tooltips when you hover over the checkboxes at the bottom. For instance, I don't know what overlaps / discontinuity means. 

When you show rulers, you might just have an overlay that says to adjust it for each monitor separately. 

You might introduce a popup or something that just mentions that some things may need the user to restart for the changes to take effect.

On the adjust speed, is that per monitor? Maybe that should be another tab like Location / Size to select which monitors to adjust speed on and by how much, or if it is all automatic, remove the option completely :)

Again, I can't thank you enough, I only hope you get the attention this app deserves and want to help with that feedback.

**Comment by mgth** [comment]
Sorry I did not come to this project for a long time.
For the adjust speed / pointer it is only available if you don't use Dpi scaling in windows, that is if every monitors are 100%. For the documentation / tooltips I Know I have to work on that...
Another thing, I only tested it with last Windows 10 version and I have reasons to think it may not work on earlier versions of windows.

**Comment by adaptabi** [comment]
Why in version 3 and 4 this checkbox and `Adjust Pointer` are disabled/unchecked?

**Comment by mgth** [comment]
This option is to take care of dpi change between screens, but if you use windows scale it is already done by the system and the effect is doubled.
