### ISSUE TITLE
Stacked monitors, mouse can go one direction, not the other

### ISSUE THREAD

**Issue by samtvn** [mgth/LittleBigMouse#285]
Hello, I have three monitors.
Two of them are stacked, the third one is on the right.
I can go back and forth from both of the stacked monitors to the right monitor.
I can go from the bottom to the top.
I cannot go from the top to the bottom monitor.
Even with fresh settings, it has this behaviour.

![image](https://github.com/mgth/LittleBigMouse/assets/95653046/53c83a31-02ac-4798-bb1e-69a45c90430c)

https://github.com/mgth/LittleBigMouse/assets/95653046/208e7a64-14a3-49c8-a0f2-83b143fd3d18

**Comment by mgfarmer** [comment]
I'm having the same problem. In my case I just added a fourth monitor on top of the cewnter monitor in my setup and my mouse get stuck up there. Do you have a guide on how to setup a dev environment. I'd like to try to fix this problem. What version of Visual Studio are you using?

**Comment by mgth** [comment]
Visual studio 2022 Preview. Dot net 8. No much more. Just pull and open the solution. Set startup project : LittleBigMouse.Ui/LittleBigMouse.Ui.Avalonia.

I think I could reproduce the problem, can you confirm it does not occur with corner crossing algo ?

**Comment by samtvn** [comment]
Yes I confirm that with corner crossing it works.

**Comment by mgfarmer** [comment]
Same,  Works fine with Corner Crossing enabled.

**Comment by mgfarmer** [comment]
I forked the repo and installed VS 2022 Preview, but I running into a brick wall with the dreaded "Loading Intellisense..." infinite loop bug. It never finishes, and I cannot build the solution. If you've seen this problem and know how to fix it, please let me know. I also installed the released VS 2022 (i.e. not Preview) and have the same problem. Googling this issue turns up many reports, but no solutions that have worked for me yet.  :(

**Comment by mgth** [comment]
fixed with pr #291
