### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Rdstrmfblynch79** [mgth/LittleBigMouse#29]
Sorry for posting this as an issue, and please excuse my ignorance, but how to I actually use this to set up a 1080 and 4k monitor to allow the mouse to correctly cross screens? I keep toggling the options and nothing is doing the trick. Could someone please walk through the process?

Thank you!

**Comment by paraDiXson** [comment]
I also struggled at the beginning. You need to make sure, that the service is started. Right click on the task symbol and choose "start". Look at your task scheduler and check, if there is an entry for the daemon to automatically launch on windows start or user login.

I attached my configuration from within the program.

![image](https://cloud.githubusercontent.com/assets/26917961/24691854/47d2b912-19d6-11e7-9658-8ba404a59683.png)

**Comment by Rdstrmfblynch79** [comment]
configuration worked. thank you so much!
