### ISSUE TITLE
colour is messed up on monitor

### ISSUE THREAD

**Issue by bouyantvigor** [mgth/LittleBigMouse#290]
while using the software, I was messing around with it until I opened up the VCP control and started moving the sliders seeing nothing change and decided to leave the settings. when I boot up my computer again, both screens were really bright. while I could change the brightness and contrast settings, the gain would never change. Do you happen to know a possible fix to this?

**Comment by EB-Plum** [comment]
Have you tried factory reset on monitor?
If that does not working, deleting the monitor in 'Device Manager' may be another option.
