### ISSUE TITLE
Trouble loading app

### ISSUE THREAD

**Issue by cicklolwut** [mgth/LittleBigMouse#297]
Having some issues getting the app to load at all. I look in task manager and I see the ui.avalonia, and the program takes a slot in the task tray, but it's just a blank space. No UI or icons in the taskbar. Unsure if maybe there's some conflicting software, or if it's my organization doing something in the background...

If there are any logs I can dig up, let me know where I can find them and I'd be glad to help sort this out. 

Device is a Lenovo Legion Go, running Windows 11 Pro 23H2
![image](https://github.com/mgth/LittleBigMouse/assets/41698233/91c4259d-0eee-4884-8259-3f1e98a9aa74)
![image](https://github.com/mgth/LittleBigMouse/assets/41698233/8aaa197f-840b-4044-9bae-cd512630bbca)
![image](https://github.com/mgth/LittleBigMouse/assets/41698233/78baf769-a420-4d93-9ac3-da65eb072346)

**Comment by cicklolwut** [comment]
Sorry, I just realized this is an existing issue, I'll post there instead ~

**Comment by PaulSorauer-IPG** [comment]
Great news! [Version 5.2.2.0](https://github.com/mgth/LittleBigMouse/releases/tag/v5.2.2) has been released and I am now running LBM successfully! Yay!
