### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by Cloudyyy1** [mgth/LittleBigMouse#299]
Hey, I ran the app > it installed and it did everything, but the it doesn't start. I tried older versions. Same issue

**Comment by nilslorand** [comment]
Same here,

updated to the newest version recently and if LBM fails to launch at startup, there is no way to get it to work, so the only way for it to work is to reboot my PC until it magically does work, which obviously is a terrible workaround.

On the old version I could at least click the "start" button ad nauseam and that sometimes worked, but the start button is greyed out way too quickly in the newest version and the start button from the taskbar does nothing.

On the older verions (4.x), regardless of the issue I had I could just close the daemon from the task manager, then re-launch the program and after a bit of "start/stop" spamming it worked flawlessly.

**Comment by BitGrub** [comment]
Same here. App won't show an interface, toolbar icon is empty/transparent and (right)clicking it doesn't do anything

**Comment by lkyu-ly** [comment]
> Same here. App won't show an interface, toolbar icon is empty/transparent and (right)clicking it doesn't do anything.
> 
> No amount of restarts fixes it. Anyone know what the last working version is?
> 
> Update: The last version 4 version didn't work until I uninstalled both versions, deleted the folder in Program Files and reinstalled it. Hope this helps someone

just the same as you. i'll try your suggestion

**Comment by lkyu-ly** [comment]
@BitGrub Good news comes that I try repeatedly as you said, unintalling and using the just lower version, and at last v5.0.1.0 works on my win11(23H2) device!
But something not so perfect is that the application cant display its text normally when windows is using a dark theme(mode).
Anyway it works. Thanks.

**Comment by kzl787** [comment]
> Same here. App won't show an interface, toolbar icon is empty/transparent and (right)clicking it doesn't do anything.
> 
> No amount of restarts fixes it. Anyone know what the last working version is?
> 
> Update: The last version 4 version didn't work until I uninstalled both versions, deleted the folder in Program Files and reinstalled it. Hope this helps someone

it works thanks

**Comment by PaulSorauer-IPG** [comment]
Great news! [Version 5.2.2.0](https://github.com/mgth/LittleBigMouse/releases/tag/v5.2.2) has been released and I am now running LBM successfully! Yay!
