### ISSUE TITLE
Trying to contribute, missing libraries

### ISSUE THREAD

**Issue by PaleoCrafter** [mgth/LittleBigMouse#30]
Hey there, this generally appears to be a great project and would help anybody with mixed-DPI screens a lot. Unfortunately, I've come across some minor issues (or one major one which is the root cause, but I'm not sure about that yet). I decided to try and iron them out myself and so went to clone your repository.
Unfortunately, building your solution as an external contributor appears to be impossible right now since you depend on a library outside of the solution space, namely something called `Erp.Notify`. It looks like you've only introduced this dependency with the most recent release, but I can't find anything by that name (including `ErpMessageBus` I found in one of the files) on Google, GitHub or NuGet.
It'd be really nice if you could provide these libraries for anyone who wants to help you with polishing this project.

**Comment by mgth** [comment]
Source code is now available.
