### ISSUE TITLE
Issue on some games where littlebigmouse allows mouse to go off focused applications

### ISSUE THREAD

**Issue by RadNotRed** [mgth/LittleBigMouse#302]
I've tested this in Apex Legends and The Finals, when I have LittleBigMouse enabled, whenever I move my mouse too fast, sometimes it let's me click on something that's on a different monitor, which then causes the game to be out of focus. This happens in fullscreen, borderless windowed, and windowed mode.

**Comment by mgth** [comment]
You may want to add an entry to
`%ProgramData%\Mgth\LittleBigMouse\Excluded.txt`
just add a line with a specific part of the path of the process to be excluded.
Add please post it here to be included in next version.
Note that you have to kill LittleBigMouse.Hook.exe to get it work.

**Comment by RadNotRed** [comment]
```
\Apex Legends\
\The Finals\
```

**Comment by mgth** [comment]
> Unfortunately it didn't work to exlude the game with the commands `\Rainbow Six\`, 

Is this a part of the path for the actual process ? Please check in task manager, I think you may try \r6siege\ or \Ubisoft\

**Comment by unsureboolean** [comment]
Same issue with Marvel Rivals and Fortnite. Is there a general fix for this yet? Seems like it's a pretty widespread issue, possibly happening on other apps as well but it wouldn't be as noticeable.

**Comment by HeadhunterKev** [comment]
> Same issue with Marvel Rivals and Fortnite. Is there a general fix for this yet? Seems like it's a pretty widespread issue, possibly happening on other apps as well but it wouldn't be as noticeable.

The fix is like two answers above your question...

**Comment by unsureboolean** [comment]
> > Same issue with Marvel Rivals and Fortnite. Is there a general fix for this yet? Seems like it's a pretty widespread issue, possibly happening on other apps as well but it wouldn't be as noticeable.
> 
> The fix is like two answers above your question...

Yeah, and that comment is from 1.5 years ago. I was wondering if there was a fix rather than having to go into my file system and change paths. It's not exactly convenient, especially when configuring multiple setups :(

I love this app, don't get me wrong. It just seems like an easy fix (on developer end, not talking about user), considering the answer is here in the comments.

**Comment by illusive-c** [comment]
Right. This issue bothered me so much, I decided to fix it myself. See the attached python script. (Change the extension to .py or .pyw)

What it does? Detects when an app in fullscreen **or borderless-fullscreen** is focused. Once detected, it sends a "stop" command to LBM. When it detects the fullscreen app is no longer in focus, it restarts the LBM's mouse behavior. 

If you want this script to run automatically, create a scheduled task that runs at windows logon. To hide the console window, run the script via pythonw.exe and not the python.exe. 

I've been testing this script for a couple of hours across various use cases and it seems to work fine.

[LBMAutotogle.txt](https://github.com/user-attachments/files/20196635/LBMAutotogle.txt)

**Comment by unsureboolean** [comment]
> Right. This issue bothered me so much, I decided to fix it myself. See the attached python script. (Change the extension to .py or .pyw)
> 
> What it does? Detects when an app in fullscreen **or borderless-fullscreen** is focused. Once detected, it sends a "stop" command to LBM. When it detects the fullscreen app is no longer in focus, it restarts the LBM's mouse behavior.
> 
> If you want this script to run automatically, create a scheduled task that runs at windows logon. To hide the console window, run the script via pythonw.exe and not the python.exe.
> 
> I've been testing this script for a couple of hours across various use cases and it seems to work fine.
> 
> [LBMAutotogle.txt](https://github.com/user-attachments/files/20196635/LBMAutotogle.txt)

Best internet stranger of the year right here! This is a much better solution than finding individual paths. Thanks!!

**Comment by JanissaryJames** [comment]
> Right. This issue bothered me so much, I decided to fix it myself. See the attached python script. (Change the extension to .py or .pyw)
> 
> What it does? Detects when an app in fullscreen **or borderless-fullscreen** is focused. Once detected, it sends a "stop" command to LBM. When it detects the fullscreen app is no longer in focus, it restarts the LBM's mouse behavior.
> 
> If you want this script to run automatically, create a scheduled task that runs at windows logon. To hide the console window, run the script via pythonw.exe and not the python.exe.
> 
> I've been testing this script for a couple of hours across various use cases and it seems to work fine.
> 
> [LBMAutotogle.txt](https://github.com/user-attachments/files/20196635/LBMAutotogle.txt)

Dose this still work? I've been trying it, and I'm not seeing any effect in Fortnite, still the same issue.

**Comment by JanissaryJames** [comment]
For anyone reading this in the future, here's another LBM auto toggler based on illusive-c's work [here](https://github.com/mgth/LittleBigMouse/issues/302#issuecomment-2878102958)

To use, just extract in the same folder as LittleBigMouse_Daemon.exe and then on the extracted file "LBM Auto Toggle.bat" right click > Send to... > Desktop (create shortcut)

Then put that shortcut wherever you want and run it whenever you need to launch one of your games. Alternatively, you can add it to the Task Scheduler to launch on log in with elevated permissions automatically.

[LBM Auto Toggle.zip](https://github.com/user-attachments/files/21339718/LBM.Auto.Toggle.zip)

**Comment by illusive-c** [comment]
> For anyone reading this in the future, here's another LBM auto toggler based on illusive-c's work [here](https://github.com/mgth/LittleBigMouse/issues/302#issuecomment-2878102958)
> 
> To use, just extract in the same folder as LittleBigMouse_Daemon.exe and then on the extracted file "LBM Auto Toggle.bat" right click > Send to... > Desktop (create shortcut)
> 
> Then put that shortcut wherever you want and run it whenever you need to launch one of your games. Alternatively, you can add it to the Task Scheduler to launch on log in with elevated permissions automatically.
> 
> [LBM Auto Toggle.zip](https://github.com/user-attachments/files/21339718/LBM.Auto.Toggle.zip)

Hey mate, yeah it's working fine. I've actually improved the script a little because it was triggering when I had youtube playing fullscreen on my side monitors. Now, the script looks for that and disables LBM only if an app is fullscreen on the main monitor(i.e while gaming).

Thanks for the binary. I wanted to keep it as Python script for safety reasons but better to have options in any case. . 

[LBMAutotogle .txt](https://github.com/user-attachments/files/21348498/LBMAutotogle.txt)

**Comment by Maxerral** [comment]
> > For anyone reading this in the future, here's another LBM auto toggler based on illusive-c's work [here](https://github.com/mgth/LittleBigMouse/issues/302#issuecomment-2878102958)
> > To use, just extract in the same folder as LittleBigMouse_Daemon.exe and then on the extracted file "LBM Auto Toggle.bat" right click > Send to... > Desktop (create shortcut)
> > Then put that shortcut wherever you want and run it whenever you need to launch one of your games. Alternatively, you can add it to the Task Scheduler to launch on log in with elevated permissions automatically.
> > [LBM Auto Toggle.zip](https://github.com/user-attachments/files/21339718/LBM.Auto.Toggle.zip)
> 
> Hey mate, yeah it's working fine. I've actually improved the script a little because it was triggering when I had youtube playing fullscreen on my side monitors. Now, the script looks for that and disables LBM only if an app is fullscreen on the main monitor(i.e while gaming).
> 
> Thanks for the binary. I wanted to keep it as Python script for safety reasons but better to have options in any case. .
> 
> [LBMAutotogle .txt](https://github.com/user-attachments/files/21348498/LBMAutotogle.txt)

Hey I would love if you helped me do this. I have no idea what to do ngl. I'm not familiar with python files and stuff. Please and thank you.

**Comment by illusive-c** [comment]
> > > For anyone reading this in the future, here's another LBM auto toggler based on illusive-c's work [here](https://github.com/mgth/LittleBigMouse/issues/302#issuecomment-2878102958)
> > > To use, just extract in the same folder as LittleBigMouse_Daemon.exe and then on the extracted file "LBM Auto Toggle.bat" right click > Send to... > Desktop (create shortcut)
> > > Then put that shortcut wherever you want and run it whenever you need to launch one of your games. Alternatively, you can add it to the Task Scheduler to launch on log in with elevated permissions automatically.
> > > [LBM Auto Toggle.zip](https://github.com/user-attachments/files/21339718/LBM.Auto.Toggle.zip)
> > 
> > 
> > Hey mate, yeah it's working fine. I've actually improved the script a little because it was triggering when I had youtube playing fullscreen on my side monitors. Now, the script looks for that and disables LBM only if an app is fullscreen on the main monitor(i.e while gaming).
> > Thanks for the binary. I wanted to keep it as Python script for safety reasons but better to have options in any case. .
> > [LBMAutotogle .txt](https://github.com/user-attachments/files/21348498/LBMAutotogle.txt)
> 
> Hey I would love if you helped me do this. I have no idea what to do ngl. I'm not familiar with python files and stuff. Please and thank you.

Download python (just google it)
Save that txt file from my post in your C: drive. 
Change it's format to .py (i.e the whole thing should be LBMAutotogle.py)
Double click on it and you're good. 
If you don't want to restart the app every time, just put it in your windows start on boot folder(Press Win+R on your keyboard and type "shell:startup" put the .py file into this folder. )
