### ISSUE TITLE
Areas of screen locked when connecting/disconnecting monitors

### ISSUE THREAD

**Issue by PoisonPrincess** [mgth/LittleBigMouse#305]
When I connect or disconnect a monitor to my pc or laptop running littlebigmouse (which I do frequently using DP switches on my pc, and often by plugging in hdmi cables to my laptop), littlebigmouse breaks, causing areas of the screen to be unreachable by the mouse. The only solutions are:
1. If the task bar is within the reachable area (not regularly), I can:
 1.a. Close littlebigmouse.
 1.b Open littlebigmouse, and refresh it
2. Ctr+alt+del, then use the arrow keys to navigate to the app and end the process.

This is obviously unideal and causes a great amount of frustration frequently.

It would be excellent if the application would simply automatically refresh when the device's monitor count changes, as refreshing always fixes the issue.

**Comment by ErnieBall** [comment]
I'm having the same issue when I switch from my 2 PC monitors to my single 4K TV.

The TV will only allow mouse movements within a 1440p boarder, despite it having the correct resolution and size configured

**Comment by ErnieBall** [comment]
While i hope, this isuue can be fixed ecentually, in the meantime i made a batch file,
that restarts LittleBigMouse.
I put the batch file in a place on my desktop, that will still be accessible, when the issue appears and it's just
a more convinient way to restart, than going through Task Manager.

Here is the contents of my batch file (this is probably not the most elegant way to do it, but it works for me )
Make sure the path to the exe file matches your actual installation 

`taskkill /f /im LittleBigMouse.Hook.exe
taskkill /f /im LittleBigMouse.Ui.Avalonia.exe
timeout 2
start /B "" "C:\Program Files\LittleBigMouse\LittleBigMouse.Ui.Avalonia.exe"`

**Comment by Mozoloa** [comment]
Same issue, waking from sleep, one of my screen always stays off, and I have to restart it, creating a short disconnect that locks one of my screen from being reached, and instead it loop back on the main one for 1440px then locks (my other monitor is in portrait)

**Comment by mgth** [comment]
As in version 5.2, lbm gets deactivated on monitor configuration change. It will automatically restart if the new configuration has been run manually. So first time just configure and re-run lbm and it should restart at each plug / unplug.
