### ISSUE TITLE
LBM v5 stops working if a game is in focus

### ISSUE THREAD

**Issue by Elduris** [mgth/LittleBigMouse#306]
This works fine in the last release of v4.
I tried disabling optimizations for windowed games and game mode and also increasing the daemon priority, but none of those helped.
Happens regardless of windowed, borderless or fullscreen mode

**Comment by Geracedf** [comment]
Seconding this. Clicking onto second monitor returns fuction, so it still is active, just not working correctly when focused on application.

**Comment by Jefemy** [comment]
This is intentional to fix issues such as #221

You can disable the filter manually by removing the directories from the `C:\ProgramData\Mgth\LittleBigMouse\Excluded.txt` file

**Comment by Elduris** [comment]
I see, that is a good feature to have, but as I didn't have that issue it did not occur to me it could be one.
Would be nice if this could be added to the new UI.
Either way, thanks for the reply.
