### ISSUE TITLE
Having Issue with app display

### ISSUE THREAD

**Issue by Moosespank** [mgth/LittleBigMouse#313]
![307175168-5816d84e-0d19-41d8-9da4-5ef3ac9d9585](https://github.com/mgth/LittleBigMouse/assets/160975421/d8c225b1-b474-4a3e-97a6-e597dc0ccb32)
I am having issues where I cant see any of my monitors on the  app

**Comment by Moosespank** [comment]
I found that this is caused by a monitor connected via HDMI instead of display like the other 2. Don't know if that helps at all

**Comment by Cristy94** [comment]
> I found that this is caused by a monitor connected via HDMI instead of display like the other 2. Don't know if that helps at all

I also have 2 DP monitors and 1 HDMI TV, and I could no longer position the monitors as I wanted, plus the devices were wrongly identified.

**Comment by mgth** [comment]
May you post your configuration file obtained with the gear button

**Comment by PaulSorauer-IPG** [comment]
Great news! [Version 5.2.2.0](https://github.com/mgth/LittleBigMouse/releases/tag/v5.2.2) has been released and I am now running LBM successfully! Yay!
