### ISSUE TITLE
Cant Open the app

### ISSUE THREAD

**Issue by Tokou14** [mgth/LittleBigMouse#324]
I have the program downloaded but it will not open. It shows as running in task manager but the window doesn't open

**Comment by kurokin** [comment]
Same too. Installed over old LittleBigMouse, then uninstalled both, rebooted, reinstalled the latest and it shows in task manager, and as a empty system tray icon.

**Comment by jacobmill20** [comment]
Also having this same issue, running on windows 11 pro

**Comment by Hugowertop2** [comment]
same issue here, running on on windows 11 home
Version 5.1.0

**Comment by CyberedCake** [comment]
Same here. I rebooted, uninstalled, reinstalled -- nothing seems to work here either.

Windows 11 Pro (10.0.22631)
Latest GPU drivers (NVIDIA GeForce RTX 3070)
Version 5.1.0

**Comment by Buesra24** [comment]
Same here.

Edition	Windows 11 Pro
Version	23H2
Installed on	‎31.‎01.‎23
OS build	22631.3296
Experience	Windows Feature Experience Pack 1000.22687.1000.0

**Comment by AndrewtheMan1** [comment]
I am not able to open the app. I have tried uninstall and reinstall but still wont open.

Version 5.1.0.0
Windows 11 Pro

**Comment by marcusv1974** [comment]
Same cant open program after download and install. Tried running in admin also.
Win 11 Home Ver 23HD
OS Build 22631.3527
all drivers upto date

**Comment by I-Cobra-I** [comment]
Has there been any fix to this yet?
I have the same issue. I downloaded all the software the programm asked for and I am using the latest version of Win11 with the latest drivers.

**Comment by AndrewtheMan1** [comment]
Hey guys I figured it out! so basically the app is open but its not open like a normal app its open in the background. Basically all you have to do is open the app and as usual nothing will happen visually but in the bottom right corner of your windows task bar click the show hidden icons button it looks like an arrow pointing up. In the hidden icons menu click little big mouse and that should maxamize the application. 

Let me know if this worked for you guys too. :)

**Comment by kurokin** [comment]
Clean installed LittleBigMouse version 5.2 , same result, no window appears, a non visible system tray icon does show up, but neither left nor right clicking does anything.  
Windows 11 23H2 (OS Build 22631.3447)

**Comment by I-Cobra-I** [comment]
> Hey guys I figured it out! so basically the app is open but its not open like a normal app its open in the background. Basically all you have to do is open the app and as usual nothing will happen visually but in the bottom right corner of your windows task bar click the show hidden icons button it looks like an arrow pointing up. In the hidden icons menu click little big mouse and that should maxamize the application.
> 
> Let me know if this worked for you guys too. :)

Thanks! That actually worked for me.
No idea why it is this way but I was able to locate the software in the hidden programs window and open it.
Setup was no issue and it now works perfectly!

**Comment by mgth** [comment]
I did change behaviour in last version; It now will open after installation and you have to choose in settings to start minimised.
