### ISSUE TITLE
Configuration disappears randomly on reboots

### ISSUE THREAD

**Issue by d0t2** [mgth/LittleBigMouse#326]
Some times when restarting the PC or waking the PC from sleep, my configs get completely reset and I can't get them to come back. The GUI shows the monitors in random locations, wrong size, everything is just gone.

Is there a way to load the configurations you get from exporting using the gear icon?

I have a 4k main monitor and a 1440p vertical side monitor. The only special thing about my setup is that I connect the displays to my main PC via displayport, while also connecting them to my work laptop via HDMI. I also have a USB switch which my mouse is connected to. So maybe there are some issues with displays and mouse being "disconnected" from the PC?

**Comment by electricsteve** [comment]
How did you fix it, I am having the same issue.

**Comment by d0t2** [comment]
> How did you fix it, I am having the same issue.

Turns out you just need to restart the program.

**Comment by electricsteve** [comment]
didn't work for me
