### ISSUE TITLE
LBM wont work when certain apps are focused

### ISSUE THREAD

**Issue by NEP1192** [mgth/LittleBigMouse#328]
With just about any game and some other applications, whenever I have them focused, the mouse movement to other screens defaults back to Win11 monitor placement/size.

Unsure if this is already an issue posted, I couldn't find one that seemed to outline this issue fully.

**Comment by jkluch** [comment]
Not sure if it's true for this application, but often what can cause this type of behavior on windows is if the app in focus is running as admin but this application isn't.  You can run into similar problems where global hotkeys don't work if a program running as admin is in focus unless you give the app that uses the hotkey admin as well

Check if the application in focus that prevents LBM from working is elevated.  If it is and LBM is not, that's probably your issue
![image](https://github.com/mgth/LittleBigMouse/assets/514150/724b4d96-bc51-4001-832d-2683a14ee190)

**Comment by NEP1192** [comment]
> Not sure if it's true for this application, but often what can cause this type of behavior on windows is if the app in focus is running as admin but this application isn't. You can run into similar problems where global hotkeys don't work if a program running as admin is in focus unless you give the app that uses the hotkey admin as well
> 
> Check if the application in focus that prevents LBM from working is elevated. If it is and LBM is not, that's probably your issue ![image](https://private-user-images.githubusercontent.com/514150/324128855-724b4d96-bc51-4001-832d-2683a14ee190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDM4MzgsIm5iZiI6MTcxMzc0MzUzOCwicGF0aCI6Ii81MTQxNTAvMzI0MTI4ODU1LTcyNGI0ZDk2LWJjNTEtNDAwMS04MzJkLTI2ODNhMTRlZTE5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQyMzUyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWM3MTE4YjMyMWI3NzJhODU3ODgyZjM5NGE2MjlhZTg0MzhkMWRkMmM1ZjZkODhmOGEzNDYwNWU2ZWRkNDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hHwyEP497tlksiSSskyhyOGlMGUrdV6HTfwBcblV1RE)

LBM is elevated and in this instance Cookie Clicker which is in windowed is not elevated.
