### ISSUE TITLE
Identical monitors merge into a single one

### ISSUE THREAD

**Issue by dmarois** [mgth/LittleBigMouse#33]
Hi
I have a problem with identical monitors (HP E242) that are seen as one monitor.
I think I've tracked the problem with the serial used to identify the screens.
The one you use to identify and save the details in the registry are the same on both screens.
ex:
screen #1 
serial: 01010101
serialNo: CN46150L5X

screen #2 
serial: 01010101
serialno: CN4609188P

and the registry show only one screen : 
Ordinateur\HKEY_CURRENT_USER\Software\Mgth\LittleBigMouse\monitors\HWP326F_01010101

It is impossible to use the software, this create an erratic behaviour on borders.

I would gladly try to fix it, but as someone else mentionned, we are missing the erp solution to rebuild the software

I'm on windows 10 and before replacing my second screen, it was working wonderfully !

Thanks !

**Comment by mgth** [comment]
I need to clean up the source and it will be available soon.

Thank you for tracking the problem.
I don't realy know how I should fix it, because some monitors do not implements Ascii Serial.

**Comment by dmarois** [comment]
Thanks for v4 beta2. the monitors are now seens as separate screens !
2 more issues, I'll open a new case and close this one

thanks !

**Comment by wwboynton** [comment]
This is not actually resolved in the latest version. This continues to occur with many models of identical monitor.

I sent @mgth an email about this on November 23 -- I am happy to take a crack at fixing this myself if I can get a little help setting up my dev environment to successfully compile LittleBigMouse.
