### ISSUE TITLE
A monitor doesnt work anymore

### ISSUE THREAD

**Issue by Pillowchewer** [mgth/LittleBigMouse#339]
Hey, I downloaded LittleBigMouse and clicked "dettach" on one of the monitors, which made it go black. Now, pressing the "attack" button doesn't bring the monitor back, so I lost a monitor from this. I know the monitor works because before booting into windows I can see the bios loading on it.

Please help me.

**Comment by mgth** [comment]
In Windows display parameters, just add it to desktop

https://support.microsoft.com/en-us/windows/set-up-dual-monitors-on-windows-3d5c15dc-cc63-d850-aeb6-b41778147554#WindowsVersion=Windows_11
