### ISSUE TITLE
Duplicate icon in system tray

### ISSUE THREAD

**Issue by Wotamin** [mgth/LittleBigMouse#347]
Ever since the update, littlebigmouse has two icons in system tray on startup. Closing one icon makes the second instance unresponsive and I'm forced to close all processes. Restarting the program "fixes" the issue, but restarting the computer brings back two icons again.

**Comment by mgth** [comment]
Check windows task scheduler, you may have two tasks for LittleBigMouse try to delete all, and recheck load at startup.
