### ISSUE TITLE
Moving between monitors 1&2 vertically locks mouse into left edge of these monitors

### ISSUE THREAD

**Issue by AlistairFielden** [mgth/LittleBigMouse#351]
![Screenshot 2024-06-02 163037](https://github.com/mgth/LittleBigMouse/assets/50730127/ad97537d-e5e1-4d35-bd30-f58f1b85abad)
When moving between screens 1 to 2 the mouse pointer locks to the left hand edge of the monitor I'm moving from. Holding <SHIFT><TAB> allows me to move the pointer away from the edge. All other transitions and scaling are working fine.

**Comment by AlistairFielden** [comment]
[LittleBigMouse.Export.gz](https://github.com/user-attachments/files/15525841/LittleBigMouse.Export.gz)
Realised the config file might be useful

**Comment by mgth** [comment]
Hi, thank you for the config, it will be helpful. As a workaround you can try using "corner crossing" algo or try moving the screens in windows config. I think there must be a bug when the side of a monitor can go to two different monitors in windows config. Try to avoid that by moving down display 3 (Again in Windows display config only keep Lbm configuration as you need.)

**Comment by AlistairFielden** [comment]
Thanks for the help. Corner crossing algorithm didn't help but moving the larger 4K display to the right in Windows display settings fixed the issue as per the screenshot.
![Screenshot 2024-06-02 180552](https://github.com/mgth/LittleBigMouse/assets/50730127/628e77c3-a442-46fb-8307-bb840f3d4cac)

**Comment by mgth** [comment]
duplicate of #325
