### ISSUE TITLE
Border Resistance Does Not Save

### ISSUE THREAD

**Issue by SaberShip** [mgth/LittleBigMouse#353]
When I add border resistance to the top of my displays then hit save (as shown below), border resistance is applied and functions as expected.

![Saving](https://github.com/mgth/LittleBigMouse/assets/6741766/129661a3-2e81-4775-b854-29e71118c8cf)

The issue arises when the application is restarted.  Once the application restarts, all configuration is loaded from before except the border resistance.  Coming back to the configuration for it, all the numbers have simply reverted to 0.0

I am running the latest version of LBM on Windows 11.

**Comment by curtis-hoffman** [comment]
I've got the same issue. Also on Windows 11. I have noticed, for some reason some of the border resistances do stay, and one of the monitors had the resistance swap from the bottom to the top border. This would happen any time my PC went to sleep.

**Comment by zaksquatch** [comment]
> I've got the same issue. Also on Windows 11. I have noticed, for some reason some of the border resistances do stay, and one of the monitors had the resistance swap from the bottom to the top border. This would happen any time my PC went to sleep.

This is exactly what is happening to me! My center monitor is set to have resistance set on the bottom, but every time, without fail, that the system goes to sleep, it reverses it.

![image](https://github.com/mgth/LittleBigMouse/assets/22183675/518155fd-f3bd-4cf5-aaa9-d090feed4fd2)

I unfortunately only found out about this software recently, but I started using it after a fresh install of Windows 11.
