### ISSUE TITLE
When playing full screen, the mouse is easily switched to the secondary screen

### ISSUE THREAD

**Issue by wozkisod** [mgth/LittleBigMouse#355]
When I play League of Legends in full screen, the mouse easily moves to other screens, causing my game to exit. Just turn it off.

**Comment by mgth** [comment]
You have to add the game process to excluded ones.

**Comment by swoy45** [comment]
Same issue here.
@mgth is there an ability to exclude processes? Can't find it.

**Comment by mgth** [comment]
Open options and you'll find excluded processes at the bottom. If the game has been running you'll find it in the "seen processes" list click on it an press "exclude"

**Comment by swoy45** [comment]
Oh I needed to update the app to see the new UI with this functionality, now it's working like a charm, thanks!
