### ISSUE TITLE
Issue with location, rulers, too sticky borders; monitor numbering different from Windows. 

### ISSUE THREAD

**Issue by MechE99** [mgth/LittleBigMouse#36]
On v4.0 beta 3- Windows 10 Pro Version 1709, OS Build 16299 having trouble setting the location properly for my 3 monitors. 2 side by side, 1 up top in the middle. Location breaks when activating the rulers
![image](https://user-images.githubusercontent.com/6039765/34220096-2fe19658-e568-11e7-852a-90b92d73525c.png) breaks to this 
![image](https://user-images.githubusercontent.com/6039765/34220120-48ad501e-e568-11e7-8191-849cbd94d9e3.png). Rulers don't show properly once activated. The issues are more than likely related. 
Borders are a bit broken, even with location set properly. Getting stuck on borders and unable to cross corners easily. Getting stuck on sliders from stardock object desktop, and windows taskbar. Would be nice to have the borders activate on reduced pointer speed.
The monitor numbering isnt the same from windows 
![image](https://user-images.githubusercontent.com/6039765/34220285-f3fabb32-e568-11e7-8da6-7ca46721709c.png)

**Comment by MechE99** [comment]
With beta4 the monitor numbering appears to be correct. Other issues location still persist, although I can move I can get them aligned with some work.  The rulers for top monitor are incorrect and only show blue on the left and right edges.

**Comment by mgth** [comment]
Could you tell me for the rulers problem with beta5 ?

**Comment by MechE99** [comment]
Hey, great work. The ruler issue is fixed, works quite well. The rulers update when using the rulers on the screen(s) to make minor adjustments and when moving the monitors within the layout panel. The alignment appears accurate. 

One thing of note with the location breaking issue is that it mostly happens when I attempt to move my 4K monitor position or click on that monitor, and not with the others now. Possibly related to the different panel size/ number of pixels, or scaling factor (1.8 vs 1.0) or that it is the primary device or much less likely that Asus panels are referenced as Ancor Communications Inc.: the actual panel manufacturer (Nvidia Control Panel pulls that name instead).

**Comment by MechE99** [comment]
Looks like this is all fixed.

**Comment by mgth** [comment]
thank you for the feedback.
