### ISSUE TITLE
How to restore backup

### ISSUE THREAD

**Issue by stom66** [mgth/LittleBigMouse#368]
I made a backup of my config which resulted in a JSON file in an archive `LittleBigMouse.Export.gz`.

Today, LBM has lost all settings about all of my monitors.

How do I restore the backup config?

**Comment by mgth** [comment]
You cannot, the file is only for debugging purpose.
The configuration is in the registry 

HKEY_CURRENT_USER\Software\Mgth\LittleBigMouse

You may save and restore this key.

The reason it's not loaded might be that your configuration does not match any layout in there. Maybe one monitor added or removed. Then you have to set it again. but you should keep monitors dimensions.

**Comment by stom66** [comment]
Thank you for the reply. 

I had replaced one of my monitors recently. The other monitor did keep their dimensions, but the overall layout was lost. 

Some way to partially restore the previous config, keep values which haven't changed (eg, the position of remaining monitors relative to each other) or view the data within the context of the software might be useful.
