### ISSUE TITLE
First time startup bug

### ISSUE THREAD

**Issue by rmthompson902** [mgth/LittleBigMouse#37]
First, let me start off by saying a huge thank you! Your software has saved me so much time. Afer buying a new 4K monitor, the Windows 10 display settings we just not enough to achieve a cohesive experience. After playing around with the software for the past hour, I have encountered a couple of bugs that I would like to address, I hope this is the right place as I am fairly new to GitHub.

The first bug I would like to let you know about is that for some reason when I first ran the program for the first time after installing, both of my monitors were overlapped and scaled on top of each other inside the program. I don't know why this would have happened, but I was able to fix it by dragging one of the monitors to another section in the location tab. Once I move one of the monitors, the issue was resolved. I was not able to recreate the issue, but I figured that I would mention it.

Ryan

**Comment by mgth** [comment]
this is a regression, positions should be deduced from windows position, but don't expect to much about this, the algo used is not so clever.
