### ISSUE TITLE
System settings dont save

### ISSUE THREAD

**Issue by Jemsuper** [mgth/LittleBigMouse#370]
Goodday,

I am trying to make the program Load at Startup. But every time after i enable it in the settings (and Start Minimized and Auto Check for update), the settings are disabled again after restarting my computer.

**Comment by mgth** [comment]
You must click the save button. I may have to change this behavior, it's not clear.

**Comment by Jemsuper** [comment]
Oh thats why then.
I am sorry, but i dont see the Save button. Where is it?

![image](https://github.com/user-attachments/assets/7f73aa03-e623-43fb-8d69-4dbb12736fca)

**Comment by knives-knife** [comment]
The save icon is the blue, hollow triangle on top of the gray, filled triangle pictured below. 
![image](https://github.com/user-attachments/assets/72879742-acff-4da5-a7ad-0e2bad56c06d)
