### ISSUE TITLE
Feature Request: Minimize button

### ISSUE THREAD

**Issue by rmthompson902** [mgth/LittleBigMouse#38]
One thing that I think that would greatly improve the program is a Minimize button to minimize the program to the tray. Personally, I think it is kind of annoying that this button is absent, even though I understand that you don't need to have the program open to have it running and working.

Ryan

**Comment by mgth** [comment]
you should have a mouse icon in tray where you can disable lbm. don't you ?

**Comment by rmthompson902** [comment]
I don't see a "mouse icon" that you are talking about. I have attached a screenshot with some text of what my LMB shows and what it does on my pc. I also linked a video of my screens of what these buttons do. As this is about window behavior, for some reason LBM is always on top. This is shown in the video. Is their a way to make LMB behave normally? Like how windows will stack on top of each other...

[Video link (Takes you to google drive)](https://drive.google.com/file/d/1hP-gI72GNDWslBNsa7SoROkBYME_tNDH/view?usp=sharing)
![minimizebtn](https://user-images.githubusercontent.com/34405801/34385414-acd5135a-eaf0-11e7-8f6e-ef9320b3db5c.PNG)

**Comment by rmthompson902** [comment]
Here is a link to the video from OneDrive... Since Google Drive compressed the video so much, this might have better quality.

[Link to OneDrive for video](https://1drv.ms/u/s!AkB5lK7RiEjWmSRwlxPMcJJ9KvxJ)

**Comment by mgth** [comment]
For the always on top, you now have a toggle button to chose it or not
I don't really see the point of the minimise button. To me it's like file properties, if you don't need it, just close it.
If I missed something do not hesitate to reopen this.
