### ISSUE TITLE
Live Update feature

### ISSUE THREAD

**Issue by rmthompson902** [mgth/LittleBigMouse#39]
I'm not exactly what the live update checkbox is for. I don't recall you mentioning this on your wiki page, that could get an update with this. It does not seem to do anything either, at least for me. On top of this, I might be nice to add a help menu inside the program that just says the exact same thing as your wiki page.

Ryan

**Comment by mgth** [comment]
It should apply modification without the need to save change, but i see it's not working now. I'll check that.

**Comment by rmthompson902** [comment]
Okay.
