### ISSUE TITLE
Mouse catching on screen edges bug

### ISSUE THREAD

**Issue by rmthompson902** [mgth/LittleBigMouse#40]
While the software is running, my mouse gets caught on the screen edges. This is very annoying for me, as I can be a bit clumsy with my mouse movement, and tend to hit the edges of my screen. This issue only happens while the program is running. The issue took place on all edges on my monitors. When my mouse becomes caught, it flickers, almost as if the program is checking for a corner or something over and over again. As for the corner cutting feature, and as far as I can tell, corner cutting being enabled or disabled does not affect the issue. My corner cutting areas work just fine. The issue only happens along edges with no monitor next to them.

Ryan

**Comment by mgth** [comment]
I can not reproduce this on my system, can you tell me more about your disposition settings ?
I have a "cosmetic" problem that look like what you says when the mouse should get to another screen in windows configuration but not in LBM, then the pointer may fliker on destination screen, and get back to previous, but it does not "catch" the mouse.

**Comment by JackSorrell** [comment]
This issue also happens on my system.

**Comment by BrentJohn** [comment]
Happens to me as well. Mouse gets caught if you move it to the absolute edge of the display area. It's not serious enough for me to stop using LittleBigMouse, but it's still a pretty big nuisance that I would greatly appreciate if fixed.

**Comment by rmthompson902** [comment]
I'm not sure what you mean by "disposition settings". If you're talking about the settings I have set up in LMB, I can provide screenshots of the menus. To show you what is happening, I have linked a video of my screens below. This should help you to understand the problem better. Some context of the video: In the video, I am constantly moving my mouse. Secondly, the mouse transition and corner cuts from screen to screen may not look proper because the screens position and scale are not exact to life nor how I have it set up in LMB. It is the best I could do in OBS though.

[Link to video (Takes you to Google Drive)](https://drive.google.com/file/d/1ZXWIaYw6Dv3FfNU62_mpcSAhZX82rPJT/view?usp=sharing)

After looking back at the video, Google Drive really compressed the file. It's kind of hard to see because it is so blurry. If you need me to upload and link the video from a different source, I can.

Ryan

**Comment by rmthompson902** [comment]
Here is a link to OneDrive, the quality might be a little better

[Link to OneDrive for video](https://1drv.ms/v/s!AkB5lK7RiEjWmSOxQtFFi3wCHzbo)

**Comment by mgth** [comment]
ok, I see now. this will be easily corrected.

**Comment by BrentJohn** [comment]
I see that this issue was corrected in the source code. Is there a compiled executable version of this? I have no idea how to code, so I need this in the other format.

Thanks!

**Comment by rmthompson902** [comment]
A compiled version would be great. Thanks!

Ryan

**Comment by rmthompson902** [comment]
I can confirm that this issue was fixed in V4.0-B5

**Comment by BrentJohn** [comment]
Awesome! This is SO MUCH BETTER! Thank you a million times!
