### ISSUE TITLE
Load at startup feature bug

### ISSUE THREAD

**Issue by rmthompson902** [mgth/LittleBigMouse#41]
For some reason, the load at startup feature did not work for me. After logging in, I stared a timer. The program did not open or initiate in the background after two minutes. For me, LittleBigMouse is not listed under Startup in Task Manager, even when the feature is enabled. I have an almost brand new rig, and the program is installed on an M.2 SSD, so I do not believe speed or startup time is an issue.

Ryan

**Comment by mgth** [comment]
Load at startup do not use regular startup from task manager, because it does not allow to run elevated privileges without asking at every startup. Nor I could use windows services cause those don't allow mouse hook for security reasons.
So I uses Task scheduler. When option ticked and save, It should create a scheduled task, that run at logon with elevated privileges. 
Can you check if the task exists ?

**Comment by rmthompson902** [comment]
In task scheduler, under active tasks, It does not seem that LMB has created a task to run on startup. What do you have the task being named? That might help me look if one exists. Also, it did not seem that any task was created by LMB's install directory, so I'm pretty positive that no task exists. 

Ryan

**Comment by bgolus** [comment]
I'm having the same issue, though I do see a task in the Task Scheduler setup to run at logon. However it seems like Little Big Mouse is crashing when my computer is going to sleep or when going to the lock screen and when logging back in the event is either still showing as running and doesn't re-launch the application, or the system tray shows two icons for LBM that disappear when hovered over as if it tried to start and second instance and both crashed.

**Comment by rmthompson902** [comment]
I don’t seem to have any of be crashing issues, however I don’t ever or my computer to sleep. Only startups and shutdowns for me.

**Comment by mgth** [comment]
should be better with beta 6

**Comment by rmthompson902** [comment]
I still do not see a task created by lbm in my task scheduler. Load at startup is still not working for me in beta 6.

**Comment by mgth** [comment]
If some of you could confirm if the problem is general (not so cause it work for me) or if some people have the same problem, please tell me.

**Comment by MechE99** [comment]
I do not have this issue. One previous version did I believe, but the task is created and works fine.

**Comment by rmthompson902** [comment]
@MechE99 , what does your task scheduler say? Just wondering so I can take another look around, as my load at startup is still not working

**Comment by MechE99** [comment]
The task name is LittleBigMouse; Triggers At log on of any user.

**Comment by bgolus** [comment]
@mgth This is working properly for me now. It no longer crashes when on the lock screen, or after bringing my computer out of sleep.

**Comment by mgth** [comment]
@MechE99, oops I forgot about that, I did it for simplifying, but the configuration is user based, so the autostart should be too.

**Comment by MechE99** [comment]
@mgth Makes sense that it should be that way if on a multi-user computer or for different workspaces.

**Comment by rmthompson902** [comment]
Load at startup is working now for me
