### ISSUE TITLE
Resizing the window bug

### ISSUE THREAD

**Issue by rmthompson902** [mgth/LittleBigMouse#42]
One last thing that I have experienced today. When resizing the window, the buttons/checkboxes/text along the border of the window does not resize with the rest of the content. Everything inside the outer border resized just fine. The issue occurred on both of my monitors. As for a fix, I do not think that the buttons up top should be resized, but the text and checkboxes along the bottom should.

As this being a very beta, but VERY useful software, I commend you for your work. I have used other beta software before, but many of the programs are just unusable. I really appreciate what you have done here. I also hope that my posts here help you out. I recall you mentioning that you just need beta testers at this point, you can count me in. I just love this software so much. It has saved me so much time. And as far as I know, you are the only one who has created anything like this, you are doing a great job.

Ryan

**Comment by mgth** [comment]
I don't get this one, maybe a screenshot could tell me more ?

**Comment by rmthompson902** [comment]
I have linked a video showing what I think might improve the program. Hope this helps. 

[Link to video (Takes you to OneDrive)](https://1drv.ms/u/s!AkB5lK7RiEjWmSWC9t1WzP6GcAdP)

**Comment by mgth** [comment]
I don't know if it really should resize, but I take note. Anyway I did not take too much care of these buttons for now (I will some day).

**Comment by rmthompson902** [comment]
Okay
