### ISSUE TITLE
Save greys out Apply/Start; Does not Apply

### ISSUE THREAD

**Issue by MechE99** [mgth/LittleBigMouse#45]
App Ver: 4.1.6581.3033

Saving before Apply/Start does not apply new settings, but greys out Apply/Start option.

**Comment by mgth** [comment]
you're right but it may be a bit tricky to fix. Anyway the way it works is a bit confusing, maybe some of you have better ideas ?

**Comment by MechE99** [comment]
Remove the save option and have Apply/start be the option which saves. Perhaps indicate that settings are saved with a check mark

**Comment by rmthompson902** [comment]
Agree with @MechE99
