### ISSUE TITLE
Edge of monitor cursor jump

### ISSUE THREAD

**Issue by JackSorrell** [mgth/LittleBigMouse#46]
When I move the cursor to the top or bottom edge of the second monitor and move it towards the other monitor slightly while touching the edge the cursor will jump onto main other monitor's same edge.

**Comment by mgth** [comment]
I don't really understand what you mean.
I have a cosmetic problem that i could not fix is when the cursor should go to second screen with windows config and not with lbm then it slightly flash on the other screen. Is that what you are talking about ?

**Comment by JackSorrell** [comment]
I don't really know how to explain it but I have attached a link to a video I shot of the issue.
https://www.dropbox.com/s/jfxu08vjf7937i7/IMG_2491.MOV?dl=0

**Comment by mgth** [comment]
Ok, this is normal behaviour if you use Allow Corner Crossing.
lbm look at mouvement direction and if it crosses another screen then goes there.
Without corner crossing screen changes are only strictly Horizontal and Verticals.

If you have ideas for better handling please tell.

**Comment by JackSorrell** [comment]
Sorry. My mistake.
