### ISSUE TITLE
Cursor refuses to move to right monitor

### ISSUE THREAD

**Issue by stevecole90099** [mgth/LittleBigMouse#47]
I have a three monitor layout. One 32" in landscape. A 27" above the 32" also in landscape. Another 27" in portrait, same model as the other one, to the right of the landscape monitors.
When LBM is active the cursor will not work on the portrait monitor. As soon as it moves on to it it bounces off back onto the other monitors.
I tried switching the monitor to landscape to see if that would fix it but the problem was still there.
All three monitors are 1920x1080.

**Comment by mgth** [comment]
I think the problem is because of wrong serial no. can you tell me in the info tab if the two screens have the same serial(hex version) and SerialNo(ascii version)

**Comment by Tremzoff** [comment]
Same problem here with very similar setup: Three 27", left and right are the same model (SAM,C7591). 
"serial" for left and right is the same (3050364D), but "SerialNo" is different (left:HTNJ400780, right:HTNJ400776). Hoperfully you can fix this, because the utility would be so useful to me.

**Comment by stevecole90099** [comment]
Sorry for the delay, I forgot about it by time I got home from work.
Yes, both of the 27" monitors show the same information.
ManufacturerCode: HSD
ProductCode: 0B5F
Serial: 00000000
Model: iL272DPB
SerialNo: 1234567890123

The information displayed under EnumDisplayDevices is correct though with one listed as Display2, and one listed as Display1 with different ID information

Display2
DeviceID: MONITOR\HSD0B5F\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005
DeviceKey: \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005
DeviceID: PCI\VEN_10DE&DEV_1C02&SUBSYS_61623842&REV_A1

Display1
DeviceID: MONITOR\HSD0B5F\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006
DeviceKey: \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006
DeviceID: PCI\VEN_10DE&DEV_1C02&SUBSYS_61623842&REV_A1
