### ISSUE TITLE
when "Corner crossing" is enabled, cursor sometimes moves from the middle of the upper side of the screen to the next screen

### ISSUE THREAD

**Issue by Shasoosh** [mgth/LittleBigMouse#49]
https://youtu.be/hPlmqvx3kQc

**Comment by mgth** [comment]
that's normal behaviour with corner crossing, if the last mouse move is in direction of the other screen border then you go there.
Many peoples seams to not like it so much. 
I used to have a maximum travel distance, maybe it's a solution. Let me know.

**Comment by Shasoosh** [comment]
Thanks for the response and the great app. Loving it so far.

I usually use the top border to stop my mouse when aiming for Chrome tabs or something similar. Making the cursor jump to another screen feels like a bug (and annoying enough to turn the feature off). I'd suggest limiting this behavior to 20-40 pixels from the screen corner. Defiantly not from the middle of the screen.

**Comment by Shasoosh** [comment]
I'd also like to add that this would sometimes happen even if you'll move the cursor straight up in one monitor and end up in another.

**Comment by mgth** [comment]
Ok, I tried different way of doing it, but for now corner crossing is not very satisfying. What is most annoying is if you go one direction and back you won't alway get to the initial place. That's by design. Limiting the travel distance might be a good compromise.

**Comment by Shasoosh** [comment]
You should check how "DisplayFusion" does it. Feels very natural.

**Comment by mgth** [comment]
you talk about "prevent mouse cursor from snagging on unaligned monitor edges" ?

**Comment by Shasoosh** [comment]
Exactly.

**Comment by mgth** [comment]
Ok, will try that

**Comment by hyperfekt** [comment]
Do you have any updates on the discussed functionality? It is honestly the only thing keeping this little utility from absolute perfection.

**Comment by mgth** [comment]
Solved with border resistance and max travel distance
