### ISSUE TITLE
Left click or right click + open on system tray icon does nothing

### ISSUE THREAD

**Issue by bgolus** [mgth/LittleBigMouse#50]
With the latest version, the open option from right clicking on the system tray icon doesn't do anything. Previous versions left clicking or that right click open option would load the GUI, but now all that happens is the cursor shows the "busy" spinning circle for a moment then returns to a normal cursor.

If I launch the application directly it opens to the GUI properly after prompting for UAC permissions.

I am running Windows 10 Pro build 16299

Also of note. The hidden system tray pop up does not go away after right clicking on the icon and has to be manually closed.

**Comment by mgth** [comment]
I had this problem once, just killing the daemon and starting it again from the gui dit it.
I think the exe crashes on start when launched from the daemon, I did not figure out why for now.
