### ISSUE TITLE
Load on startup

### ISSUE THREAD

**Issue by pjmavcom** [mgth/LittleBigMouse#53]
First thanks for this program, aside from mouse jumping bugs, this is great. But I cant get it to load on startup. Ive got the option checked, Ive got it in the windows startup folder and in the registry. I get a UAC message popup on startup, but it still doesnt load. Ive got Windows 10 x64. Any help would be appreciated. Thanks!

**Comment by pjmavcom** [comment]
Seems the cause for this has something to do with USB 3 monitors maybe. Switched to HDMI and it loads on startup

**Comment by just4747** [comment]
On latest version, 4.1.6598.15330 (installed 4/16) using Windows 10, LittleBigMouse will only successfully "Start" on some occasions. It always shows up in the taskbar fine, but at least 50% of boots, I have to manually right click the icon and click "Start" so it turns its adjustments on.

**Comment by mgth** [comment]
Should be fixed as of 4.2

**Comment by just4747** [comment]
> Should be fixed as of 4.2

Thanks!

**Comment by just4747** [comment]
FYI - on the new version this is STILL happening. First few times, it loaded and enabled automatically upon boot up on Windows 10. But just now, even though the program was running in the bottom right of task bar, it wasn't automatically enabled just like before...
