### ISSUE TITLE
Mouse cursor moves to wrong monitor at unaligned edge

### ISSUE THREAD

**Issue by wouter140** [mgth/LittleBigMouse#57]
First of all, this app is great. Something that should be implemented into windows as default.

I am having a little issue, however. 
I have unaligned monitors. My left one is 1080p, middle 1440p and right 1080p. The middle one is scaled in windows at 125%. The middle one is also a little higher than the side ones. 
The problem is that when I move my mouse from the bottom left of the right monitor to the left, it snaps to the left monitor and not the middle one. (even with corner crossing enabled).

Little image showing it. The mouse snaps like the arrows and just skips the middle monitor.
![monitor_snap](https://user-images.githubusercontent.com/14236223/39317874-f81b46aa-497c-11e8-9a1d-c04d10837bbf.png)

Is this intended or a bug? If it's intended, this might be good as an option.

**Comment by mgth** [comment]
Yes, that's "by design" I juste search the next monitor un the mouse direction. We could have an option for max travel distance. It's already been asked for other purpose.
