### ISSUE TITLE
USB Hub BSOD...

### ISSUE THREAD

**Issue by cgalbreath** [mgth/LittleBigMouse#58]
I have been using LittleBigMouse for a few weeks and in that time
my USB switch has started causing a weird issue where when I would
swap between devices my primary PC that has LittleBigMouse would
BSOD with what seemed to be a driver issue. After some troubleshooting
I have narrowed it down to being LittleBigMouse, I have not yet determined 
why this is happening but I am going to do some more testing to try and 
give more information to help solve this problem...

This is probably a niche issue to a specific setup ect. So unsure exactly
how much time spent on this will be worth while in the end

**Comment by mgth** [comment]
It maybe related to display changes détection. I could at l'East add an option to deactivate it.

**Comment by cgalbreath** [comment]
I am willing to test if you implement the function if you implement
