### ISSUE TITLE
Make mouse speed adaptation configurable

### ISSUE THREAD

**Issue by mgth** [mgth/LittleBigMouse#6]

**Comment by Willem68** [comment]
Awesome tool!
Just a question related to this issue. I have a dual setup with an HD and UHD monitor. The mouse pointer speed under Windows 10 is set at maximum to fit my desired speed on the UHD monitor. The speed on the HD monitor is then too fast. So I tried LittleBigMouse to adjust this. The program is able to produce equal speeds on both monitors, but it makes it also slower on the UHD monitor. Is there a way to enhance the speed on the UHD monitor?

**Comment by mgth** [comment]
If you have a logitech mouse you can use it's control panel that is independent to windows configuration.
In a future version I might add a mouse speed control.
