### ISSUE TITLE
Monitors not appearing in program

### ISSUE THREAD

**Issue by onedollarwilliam** [mgth/LittleBigMouse#60]
Looking at the images and posted in some of the previous issues I know that there should be examples of my monitors in the program when I open it, but it's just blank. Additionally when I copy the config info the monitors section doesn't contain any information. 

![lbm-issue](https://user-images.githubusercontent.com/2219923/39558493-085ece4e-4e5d-11e8-8259-5fbd5b3bd3af.png)

`{
  "Config": {
    "AllScreens": [],
    "Id": "",
    "AutoUpdate": true,
    "PrimaryScreen": null,
    "PhysicalOutsideBounds": "0,0,0,0",
    "PhysicalBounds": "0,0,0,0",
    "Enabled": true,
    "LoadAtStartup": true,
    "LoopAllowed": true,
    "LoopX": false,
    "LoopY": false,
    "IsRatio100": true,
    "AdjustPointerAllowed": true,
    "AdjustPointer": false,
    "AdjustSpeedAllowed": true,
    "AdjustSpeed": false,
    "AllowCornerCrossing": false,
    "HomeCinema": false,
    "Pinned": false,
    "ConfigLocation": "0,0,0,0",
    "AllowOverlaps": false,
    "AllowDiscontinuity": false,
    "MaxEffectiveDpiX": 0.0,
    "MaxEffectiveDpiY": 0.0
  },
  "Monitors": []
}`

I'm using a pair of Dell 21 inch monitors and a Vizio HD TV, and, due to the design of my particular video card, each one is connected with a different interface: one monitor on DVI, one monitor on DisplayPort, and the TV via HDMI.

**Comment by mgth** [comment]
that's weird, what video card do you use ?

**Comment by onedollarwilliam** [comment]
It's a 4GB MSI GTX 960. From what I gather looking online it's not the standard model. It seems to be a little shorter than the typical boards, and they've swapped two (of the three) DisplayPorts for a second DVI port.

**Comment by onedollarwilliam** [comment]
I found a fix. When I looked in Dxdiag the monitors were each listed with an "x" so I went into Device Manager, and they were all listed as "PNP-Monitor (Standard)". I installed the Dell specific drivers for the two monitors, and switched the TV to "Generic PNP Monitor" and that has resolved the issue.

**Comment by takashi1kun** [comment]
@mgth  I have the same problem as him, whit the difference that i cannot do that, my monitors do not have specific drivers.
