### ISSUE TITLE
When in games the cursor flickers at the edge of screens

### ISSUE THREAD

**Issue by VinceBT** [mgth/LittleBigMouse#61]
When in games (like League of Legends) that require you to use the edge of the screen to move the camera, the cursor flickers and teleports itself at random Y position on the edge.

**Comment by VinceBT** [comment]
I enable it all the time because it really fixes my resolution problem with my screens, but I don't see why I should have to disable it manually for gaming.

If it could detect fullscreen and borderless fullscreen I would let it run 24/24.

**Comment by Lil-Jening** [comment]
I would love a feature to disable LBM while a process is running. Allowing a user created blacklist.

**Comment by VinceBT** [comment]
I made this @mgth @GameGrime https://github.com/VinceBT/LBMM
