### ISSUE TITLE
3d monitor not detected/working

### ISSUE THREAD

**Issue by Leakysandwich** [mgth/LittleBigMouse#66]
I do first have to say thanks for this app, it seems to do exactly what I would want.

However, I have a similar issue to some other posters:

1x Acer screen in middle (2560x1440), 2x Samsung screens to the sides (1920x1080)
The left and middle screen works perfectly, but the mouse refuses to go to the rightmost screen (one of the samsungs)
However, additionally, the right most screen does not get picked up on initial app-open. Only once i move a different screen in the Location tab, then the 3rd (right) screen pops up in the view - but even moving it around and applying the settings, it will not accept the mouse to move into this screen...

Config copied to clipboard: https://pastebin.com/8Rtv4i5k
Screenshot: https://imgur.com/a/A0QIEBl

**Comment by kamikakushi** [comment]
Same issue here.

**Comment by Priva-au** [comment]
I'm just going through and bumping this issue up. Seems to only affect people when the two side monitors are the same brand and model. 

Other thread here: https://github.com/mgth/LittleBigMouse/issues/80

**Comment by Sputnikcer** [comment]
I've posted a hotfix for this issue on https://github.com/mgth/LittleBigMouse/issues/132

**Comment by strazto** [comment]
likewise, 

>  Seems to only affect people when the two side monitors are the same brand and model. 

That's the case for me
