### ISSUE TITLE
Mouse cursor should catch on monitor edges while dragging a window

### ISSUE THREAD

**Issue by AntiBlueQuirk** [mgth/LittleBigMouse#68]
Under normal Windows behavior, if the mouse cursor is moving slow enough while dragging a window, it will "catch" on left and right monitor edges. This is to make it easier to trigger Window's "Snap" feature, to "maximize" the window to half the screen. When LBM is enabled, the "catch" doesn't happen, interfering with the gesture.

Steps to reproduce:
- With LBM disabled, drag a window at a low speed to a left or right edge between monitors: The "Snap" gesture is initiated, and the mouse catches on the edge, staying on the current monitor. Releasing the mouse snaps the window to half the monitor. This is the expected behavior.
- Enable LBM, then attempt the same gesture: The "Snap" gesture is still initiated, but the cursor does not stop. When the mouse is released, the window frequently snaps to the wrong monitor.

Suggested solution:
- While dragging a window, make the cursor stop on monitor edges, until the user releases the mouse button, moves away, or moves far enough "through" the edge.

Other notes:
- The gesture is also triggered by dragging a window to a corner of a screen, in which case the window fills that corner, instead of a half.
- A similar gesture "Dock maximize" is triggered by dragging the mouse to the top of a monitor. I haven't tested it, but I imagine it is affected by a similar issue.
- The both gestures can be controlled with `REG_SZ:"HKEY_CURRENT_USER\Control Panel\Desktop\DockMoving"` and `REG_SZ:"HKEY_CURRENT_USER\Control Panel\Desktop\WindowArrangementActive"`; if either key is not set to "1", then the catching behavior on edges is not needed.

**Comment by SoundedSquash** [comment]
A workaround is to just use ![image](https://user-images.githubusercontent.com/20405599/59718883-b365b600-91e0-11e9-9924-96e3a62380d6.png) + Left/Right Arrow key to snap the window where you want.

**Comment by Timmyfox** [comment]
Came here to mention this as well. I quite regularly use Snap to arrange my Windows and this is probably the only issue that is holding this otherwise excellent piece of software.

Hopefully we can see a fix for this at some point in the not-too-distant future!

**Comment by TheInfamousAlk** [comment]
Also have this issue. I could use the key combo shortcut, but often my hand is not at my keyboard, and it's hard to change my habit of slamming the window upwards to maximize it. I can't conveniently use this software until this is fixed.

**Comment by Migushthe2nd** [comment]
As a heads up, Windows 11 removes this behaviour

**Comment by EvaisaGiac** [comment]
> As a heads up, Windows 11 removes this behaviour

You can reenable this behaviour in windows 11 actually.
