### ISSUE TITLE
Spacedesk causes program to not work or scale.

### ISSUE THREAD

**Issue by JasperTecHK** [mgth/LittleBigMouse#71]
In short, I'm using a tablet as a third monitor. disabling spacedesk allows the software to work fine on the two different monitors flawlessly, but when spacedesk is running, the GUI doesn't pop up and scaling across all three monitors, or even the original two, fail to run. 

What I have noticed though, is when spacedesk disengages the tablet as a monitor, the main display flashes for a quick second, before returning to normal. Perhaps, spacedesk does the screen creation by re-duplicating/modifying display driver/execution which causes littlebigmouse to get confused?

**Comment by mgth** [comment]
I will give it a try.

**Comment by mgth** [comment]
As of 4.2 it should work
