### ISSUE TITLE
Possible fix for LBM not starting on logging in, Win10

### ISSUE THREAD

**Issue by Cafem** [mgth/LittleBigMouse#74]
Like many I've had similar issues with this not starting on launch, and followed a lot of the possible fixes and guides. I tried a few of my own; part of the issue for me is that UAC is required for the LittleBigMouse_Control.exe to run. I mention it's a possible fix not to be clickbaity, since mine does launch and run on startup, but I couldn't tell you at this time without testing what exactly was the tipping point.

That being said;

Task scheduler settings;

- General tab - Run only when user is logged on, run with highest privileges
- Triggers tab - At log on with named user account
- Actions tab - start a program, details "C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe" with arguement "--start" (remove "")

The rest was removing the UAC prompt for LittleBigMouse_Daemon.exe and LittleBigMouse_Control.exe using the Compatibility Administrator toolkit provided with the Windows ADK, which can be downloaded from Microsoft here (https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install)

- Run ADKsetup.exe. Specify location of install. Ignore size of install for the moment.
- Choose anonymous usage data settings
- Licence agreement
- Untick all features except for Application Compatibility Tools (first option). Install should be roughly 8MB after extra features removed

Once installed;

1. Run Compatibility Administrator from start menu, or C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Application Compatibility Toolkit by default install location. Choose 32 or 64-bit as required; I ran 64bit
2. In the Toolkit, hit Fix from the icon ribbon
3. Set name of program and/or vendor, and specify location of LittleBigMouse_Daemon.exe. Hit Next
4. Under 'Additional compatibility modes', choose 'Run as Invoker'. Hit Next
5. Under Compatibility Fixes, ensure 'Run as Invoker' is also ticked. Hit Next
6. Under Matching Information screen, hit 'Auto-Generate' button. Hit Finish
7. Hit 'Save' from icon ribbon. Save in same folder as target .exe
8. Once saved, select File and select install. Dialog box should say successfully installed.
9. Repeat steps 1-8 exactly, but choose LittleBigMouse_Control.exe instead. 

My settings for each .exe of these are as follows;

LittleBigMouse_Daemon.exe
LittleBigMouseD.sdb (I set this in steps 3 and 7)
Run as Invoker (step 4)

LittleBigMouse_Control.exe
LittleBigMouseC.sdb (I set this in steps 3 and 7)
Run as Admin (step 4)

Both .sdb files saved in the same folder.

Feel free to test settings and confirm if this will work. Obviously your mileage may vary, and I cannot offer much support much beyond what I've written.

**Comment by DJCool1** [comment]
For me, I didn't need to do all that second part for UAC, just make a task in task scheduler and check the box "run with highest privileges".
