### ISSUE TITLE
Load at startup not working

### ISSUE THREAD

**Issue by kenner03** [mgth/LittleBigMouse#78]
I'm using 4.1.6598.15330

**Comment by coffeymatt** [comment]
Ditto, doesn't run on startup for me. (otherwise excellent, works well)

**Comment by etvoilaletravail** [comment]
Same in my case, works well, but won't load on startup. I tried adding a shortcut to my startup menu with no result.
Additionally, it will pop up a windows UAC message «unknow editor» that i have to accept each time I launch it manually. I tried setting every shortcut (the one in the startup menu i manually added, and the one on my desktop) to start as admin but the popup still displays on each launch.

**Comment by MechE99** [comment]
The task it creates in task scheduler should look like this:
![image](https://user-images.githubusercontent.com/6039765/51691765-43942c00-1fb0-11e9-8ab4-ef0eeebf45fa.png)

Program/Script:
C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe
Add arguments (optional): --start
Start in (optional): C:\Program Files\LittleBigMouse\

Run with highest privileges

**Comment by mgth** [comment]
see #63
