### ISSUE TITLE
Task Scheduler Command Needs Quotes

### ISSUE THREAD

**Issue by Shadetheartist** [mgth/LittleBigMouse#82]
The task scheduled by the program is apparently not valid on my machine, win 10. The "Program/Script" options requires quotes around it for the program to launch properly.

Also see https://stackoverflow.com/questions/13618945/why-windows-7-task-scheduler-task-fails-with-error-2147942667

**Comment by permster** [comment]
Yeah I had the same issue as well.  Looks like this should be a simple update on this line to add quotes:
https://github.com/mgth/LittleBigMouse/blob/d34eb0168296159b5738ab59e13a07bd81cc353d/LittleBigMouse/Daemon/LittleBigMouseDaemon.cs#L311
