### ISSUE TITLE
LBM wont start after windows 10 update

### ISSUE THREAD

**Issue by MonsterArtur** [mgth/LittleBigMouse#84]
LBM version: 4.1.6598.15330
Wind10 ver: 1903 (18346.1)

When start LittleBigMouse from menu, i can see icon in tray, and few seconds later its gone. No window show up.

**Comment by PharaohJoe** [comment]
Same.  Looking at Event Viewer it seems that there's an issue with kernelbase.dll? Not too sure

**Comment by gbaman** [comment]
Can confirm am seeing the same issue.

**Comment by mgth** [comment]
It should work now with 4.2
