### ISSUE TITLE
Difficult to See Disabled Box

### ISSUE THREAD

**Issue by Kesslerb2** [mgth/LittleBigMouse#85]
Love the program, was just wondering if you could change the "enabled/disabled" texture for the check boxes. Not sure if I'm colo blind, but it's nearly impossible for me to tell the difference. I tried to check it and it would almost instantly uncheck since the box was disabled, left me confused for a second.

![Capture](https://user-images.githubusercontent.com/45176354/54078734-8b8abc00-429b-11e9-87ee-9f0467badfc1.PNG)
-Adjust Speed and Adjust Pointer are disabled but it's really hard for me to see.

Thank you for open sourcing this project!

**Comment by mgth** [comment]
It is better now.
