### ISSUE TITLE
reset color settings

### ISSUE THREAD

**Issue by jeytee84** [mgth/LittleBigMouse#90]
So I've tried the VCP  settings part of the software and kinda screwed up the colors on my otherwise pretty well calibrated main monitor. Any idea how i could reset the changes made by LBM?

**Comment by mgth** [comment]
You might just reset on the rgb settings on the monitor.

**Comment by atticusnari** [comment]
I finally found out how to fix it. All you have to do it install this program called [ControlMyMonitor](https://www.nirsoft.net/utils/control_my_monitor.html), select the monitor you're having trouble with and change the variables of "Video Black Level: Green" and "Video Black Level: Blue" to whatever default values you had them originally!
