### ISSUE TITLE
Crashing Immediately

### ISSUE THREAD

**Issue by nolifedigital** [mgth/LittleBigMouse#91]
Program was working fine. All of a sudden, it starts crashing immediately. Doesn't open on startup. No task in manager. Not sure what happened.

**Comment by Jonathandlm** [comment]
I have the same issue. Here's the Log:

`
Faulting application name: LittleBigMouse_Control.exe, version: 4.1.6598.15330, time stamp: 0x5a683634
Faulting module name: CRYPT32.dll, version: 10.0.17763.1, time stamp: 0xb2fbbe58
Exception code: 0xc000001d
Fault offset: 0x000000000000917d
Faulting process id: 0x43d8
Faulting application start time: 0x01d504fc2a36c7fe
Faulting application path: C:\Program Files\LittleBigMouse\LittleBigMouse_Control.exe
Faulting module path: C:\WINDOWS\System32\CRYPT32.dll
`

**Comment by mgth** [comment]
changed many things, so try with last version and post again if still there.
