### ISSUE TITLE
"Adjust Speed" and "Adjust Pointer" options disabled even when "Enhance pointer precision" is turned off

### ISSUE THREAD

**Issue by stravant** [mgth/LittleBigMouse#94]
The system only adjusts the mouse speed to respect the scaling when enhance pointer precision is turned on. I don't want to turn the option on because I like linear mouse movement, but I want that linear movement to be consistent across screens. 

I don't know if LittleBigMouse could currently correctly handle this case even if the option weren't disabled, but it is a use case that has been missed.

**Comment by mgth** [comment]
no, it should work, but only when all screens at set to 100% because windows already deal with mouse speed when screen ratio are defined. LBM could take care of the remaining difference. Tell me if there is need for that.
