### ISSUE TITLE
App Doesnt Start Anymore After Update?

### ISSUE THREAD

**Issue by nadimalam** [mgth/LittleBigMouse#95]
Ive been using the old version of this app from Jan, i think it was LittleBigMouse_4.1.6598.15330.

Since my last windows update about a week or two ago i noticed that the app wasnt auto starting anymore. 
I visited the github page and saw there was a new version out, LittleBigMouse_4.2.7124.42685.

I installed this update, but since the install the app no longer starts at all for me :( 

Any idea what could be wrong? I dont even get an icon in system try.

Thanks.

**Comment by NickAcPT** [comment]
Also got this to happen to me.
I've tried attaching a debugger with dnSpy and got this message:
"Could not load type 'HLab.Base.IEventHandlerService' from assembly 'HLab.Base, Version=1.0.6598.15316, Culture=neutral, PublicKeyToken=null'."

**Comment by mgth** [comment]
ok, there must be a problem with dll versioning, i will check that.

**Comment by dlxmax** [comment]
I had the same problem. Updated from 4.1.something to the latest and it wouldn't run, even manually after reboot. Uninstalled/reinstalled and it works again.
I love this app. Thank you.
