### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by NickAcPT** [mgth/LittleBigMouse#96]
I've been trying to build the project but I haven't been able to because there are missing projects:

![Image](https://i.imgur.com/A3emc6a.png)

Visual Studio shows them as unloaded because the code isn't in the repo.

**Comment by mgth** [comment]
yes, hlab is another project that will be posted soon.

**Comment by PassiveModding** [comment]
when are you planning on posting? I would like to make some personal tweaks but can't

**Comment by Spiritreader** [comment]
I'd also be very interested in this.

My university is offering a course about guided open source software defelopment and I would've hoped to contribute to this project at the end of this.

With that the requirement to build the project arises, so I'd be very glad if hlab would be made public. 

Thanks!

**Comment by mgth** [comment]
https://github.com/CHMP-HLab/HLab
