### ISSUE TITLE
"Size" control not working as expected

### ISSUE THREAD

**Issue by dlxmax** [mgth/LittleBigMouse#98]
Using the latest version (4.2.7124.42685), I'm trying to input correct width and height figures for a generic monitor under the "size" tab, but when I input either the X or Y axis, the other axis changes as well. I imagine it's trying to keep the predetermined incorrect aspect ratio. I also see an undocumented checkbox at the intersection of the two axes, perhaps for aspect ratio lock, but even unchecked the problem still occurs.

**Comment by zix7** [comment]
I've got the same issue, it seems to fix the aspect ratio sort of when i put in the full monitor size, however the LBM still doesnt function correctly after doing so

**Comment by dlxmax** [comment]
As a work-around, if the monitors are side-by-side, only input the height. The mouse will track correctly.

**Comment by Picklejar05** [comment]
I have the same problem, but **_all_** of the numbers change! I hope this is fixed..

**Comment by ThomasHFWright** [comment]
I'm having the same issue, I have 1 monitor above 2 smaller ones so quite an irritating issue as the there is one spot where the mouse will not move to a certain monitor.
Is there a config file somewhere that can be used to manually override the settings?
